Feat/bot
torin-asakura/shdvor pull request #104
Opened 2024-10-09 15:27 UTC by kirill-ivanovvv

2024-10-17 11:21 UTC, Nelfimov requested changes

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/apollo-adapter/src/index.ts
> +export * from './use-cases/index.js'
`use-case` - это прерогатива только `application`. Здесь это могут быть только сервисы

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/tsconfig.json
> +  // "extends": "../../../tsconfig.json",
комменты

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/constants/entity.constants.ts
> +export const MIKRO_ORM_CONFIG = 'MIKRO_ORM_CONFIG'
используй `Symbol`

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/module/mikro-orm-adapter.module.ts
> +    // await this.createMigration()
коммент

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/getters/get-formatted-context.getter.ts
> +    // userUsername: ctx.message?.from?.username,
коммент

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/helpers/check-formatted-context.helper.ts
> +      throw new Error(`cannot acces ${contextKey}`)
`access`

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/helpers/check-formatted-context.helper.ts
> +      throw new Error(`cannot acces ${contextKey}`)
надо стандартизировать ошибки. Создать отдельный класс ошибки для телеграма и использовать его

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/use-cases/check-chat-conversation.use-case.ts
> +  constructor(private readonly tgsnakeAdapterService: TgsnakeAdapterService) {}
зачем? У тебя есть синглтон который ты переиспользуешь

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/use-cases/get-ru-locale.use-case.ts
> +class GetRuLocaleUseCase {
Надо использовать локализацию через отдельный адаптер. Ранее скидывал библиотеку. Если хочешь это вынести в следующую итерацию - помечай `TODO`

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/use-cases/send-message-with-markup.use-case.ts
> +// TODO сделать из сенд-мессейдж - один файл.
не очень понял что хочешь сделать

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/use-cases/send-message-with-markup.use-case.ts
> +import { getRandomBigIntGetter }                from '../getters/get-random-big-int.getter.js'
импорт из `index.js`

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/contexts/orm/application-module/package.json
> +  "name": "@orm-client/application-module",
такого контекста быть не может - контекст определяется бизнесом либо областью с которой ты работаешь

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/contexts/orm/application-module/package.json
> +  "name": "@orm-client/application-module",
в общем тебе надо его разнести по другим контекстам

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/classes/question-answer-pair.abstract-class.ts
> +abstract class QuestionAnswerPair {
1. странный нейминг, непонятно что происходит
2. `classes` - это к чему?

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/package.json
>    "license": "BSD-3-Clause",
пишу в целом по пакету:
1. мы пишем на клине, а у тебя в юзкейсах `command`
2. юзкейс - это логика приложения. Полный цикл - что то пришло на вход и что-то вышло, а у тебя в сервисах целый зоопарк функционала

Пересмотри этот момент. Повторяющиеся действия можешь вынести хоть в `common`, хоть в отдельные вспомогательные сервисы

2024-10-17 11:21 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/package.json
>    "license": "BSD-3-Clause",
и еще посмотреть на `appointment-conversation`, то в нем одни `await` и ничего не возвращается. Может стоит возвращать что-то из сервисов, чтобы потом с этим данными можно работать? Я понимаю что вся беседа телеги лежит в контексте, но так выходит мы контекст гоняем туда-сюда и не знаем что в нем внутри

2024-10-17 13:14 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/constants/entity.constants.ts
> +export const MIKRO_ORM_CONFIG = 'MIKRO_ORM_CONFIG'
символ только для этого параметра или для всех констант?
нашел пример, символ не везде используется - https://github.com/atls/serverless-yandex/blob/5cfdb91dcc89a9490f7e733b55fbd3048ecccf21/adapters/ffmpeg/src/constants/ffmpeg.adapter.constants.ts#L1

2024-10-17 13:18 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/tgsnake-adapter/src/helpers/check-formatted-context.helper.ts
> +      throw new Error(`cannot acces ${contextKey}`)
этот класс будет испольоваться только в текущем адаптере или, например, для бота-оператора тоже -> вынести его в `@globals`?

2024-10-17 13:22 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/constants/entity.constants.ts
> +export const MIKRO_ORM_CONFIG = 'MIKRO_ORM_CONFIG'
Только для токен инжекта

2024-10-17 13:23 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/helpers/check-formatted-context.helper.ts
> +      throw new Error(`cannot acces ${contextKey}`)
В рамках адаптера. В таком случае в ошибках в логах ты сможешь отследить кто выбросил ее

2024-10-17 13:27 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/tgsnake-adapter/src/use-cases/get-ru-locale.use-case.ts
> +class GetRuLocaleUseCase {
https://www.npmjs.com/package/nestjs-i18n

2024-10-17 13:44 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/classes/question-answer-pair.abstract-class.ts
> +abstract class QuestionAnswerPair {
абстракный класс, который создает пару вопрос-проверка ответа(+ выход из диалога/запись ответа)

на основе этого класса создаю 9 таких классов (сервисов). пара вопрос-ответ

1. нейминг уже третья попытка. не понимаю как это функционал еще можно обобщить
2. директорию `abstract-classes` назвать - будет нормально? лежал в куче с сервисами, подумал что лучше вынести.

2024-10-17 13:49 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/classes/question-answer-pair.abstract-class.ts
> +abstract class QuestionAnswerPair {
Тогда это должно быть в интерфейсах.

2024-10-22 07:57 UTC, Nelfimov requested changes
уже гораздо лучше. К следующему ревью проверь:
- работу в деве
- работу в билде
- вышли скринкаст работы с ботом

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +            path: path.join(dianemPath, '../locals/'),
проверь в деве и билде чтобы схватывались файлы. Вероятно придется делать для билда отдельный путь, а так же копировать статику

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +            watch: true,
в билде не нужен

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/i18n-adapter/src/services/i18n.service.ts
> +  getWelcome(): string {
хорошо подошел. Сделай просто через `get welcome` - тогда будет простой геттер

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/interfaces/tgsnake-adapter-error.interface.ts
> +class TgsnakeAdapterError extends Error {}
это должно быть в `errors` адаптера

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/helpers/check-formatted-context.helper.ts
> +import type { TelegramBotFormattedContextKeyType } from '@booking-telegram-bot/tgsnake-adapter'
если это локальные импорты - пиши через относительные пути. Так читаемее

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/services/create-conversation.service.ts
> +        conversation.wait('msg.text', (conversationCtx: TgsnakeContextType) => {
`msg.text` лучше вынести в енамы если tgsnake их не предоставляет

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bot-service-entrypoint.module.ts
> +    MikroOrmAdapterModule.register(),
это и ниже - можно импортировать тут а можно в инфраструктуру. Объективно у тебя инфраструктура знает о существовании адаптеров, а вот энтрипоинт - ему пофигу

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/ports/orm.port.ts
> +class OrmPortimpl implements OrmPort {
это `repository`. Т.е. на каждую энтити должен быть свой репозиторий

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/ports/i18n.port.ts
> +  getWelcome(): string {
либо здесь перевести на геттеры

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/interfaces/telegram-client.interfaces.ts
> +  // replyMessage: (text: string) => Promise<void>
коммент?

2024-10-22 07:57 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/ports/i18n.port.ts
> +export abstract class I18nPort {
какой нибудь `MessagePort` может быть тоже хорошим неймингом

2024-10-22 08:45 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/ports/orm.port.ts
> +class OrmPortimpl implements OrmPort {
типо `AppointmentDataPort`?

2024-10-22 08:47 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/ports/orm.port.ts
> +class OrmPortimpl implements OrmPort {
`НазваниеЭнтитиRepository`

2024-10-22 08:51 UTC, kirill-ivanovvv commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bot-service-entrypoint.module.ts
> +    MikroOrmAdapterModule.register(),
адаптеры перенест. 
в ентрипоните должны быть **и** `application` **и** `infrastructure`?

2024-10-22 13:19 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +            path: path.join(dianemPath, '../locals/'),
ничего не менял, в билде так работает. проверил

2024-10-22 14:28 UTC, Nelfimov approved these changes

2024-10-22 14:28 UTC, merged