Feat/rest api endpoint
torin-asakura/shdvor pull request #110
Opened 2024-10-25 12:04 UTC by kirill-ivanovvv

closes https://github.com/torin-asakura/shdvor/issues/106

2024-10-25 12:09 UTC, kirill-ivanovvv commented
@Nelfimov 

- создал контекст `апи`
- у него создал слой `инфрастуктуры`
- слой `application` не создавал - взаимодейстую с уже готовым функционалом из `@telegram-bot/application-module`

### порт для сервиса зашил в переменную окружения - 
`BOOKING_TELEGRAM_BOT_PORT`

2024-10-25 12:12 UTC, Nelfimov requested changes

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/mikro-orm.config.ts
> +        name: '@site adaptation',
см. выше какое название должно быть

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/controllers/booking.controller.ts
> +export class CatsController {
это что за контроллер кошек??

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/errors/api.error.ts
> +class ApiError extends Error {}
Должен быть месседж дающий понять что за ошибка, а не просто наследование

2024-10-25 12:12 UTC, Nelfimov commented on site/api/booking/src/booking.api.ts
> +  const fetchUrl = `http://localhost:${bookingTelegramBotPort}/booking`
а почему ты только порт вынес как переменную окружения?

2024-10-25 12:12 UTC, Nelfimov commented on fragments/booking-fragment/src/initial/initial.component.tsx
> +    console.log(response)
консоль логи?

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/services/booking.service.ts
> +    throw new Error('body is not string')
должна быть своя ошибка

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/module/mikro-orm-adapter.module.ts
> +      providers: [configProvider, ModuleRef as Provider],
зачем модульреф?

2024-10-25 12:12 UTC, Nelfimov commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +    const providers = [...serviceProviders, HttpAdapterHost, ModuleRef as Provider]
зачем здесь httpадаптерхост?

2024-10-25 12:17 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/api/infrastructure-module/src/errors/api.error.ts
> +class ApiError extends Error {}
создать старические методы?

2024-10-25 12:19 UTC, kirill-ivanovvv commented on site/api/booking/src/booking.api.ts
> +  const fetchUrl = `http://localhost:${bookingTelegramBotPort}/booking`
контейнеры не по локалхосту общаются?

2024-10-25 12:26 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/errors/api.error.ts
> +class ApiError extends Error {}
нет. У тебя ошибка должна в месседже давать контекст - что и где произошло

2024-10-25 12:26 UTC, Nelfimov commented on site/api/booking/src/booking.api.ts
> +  const fetchUrl = `http://localhost:${bookingTelegramBotPort}/booking`
нет конечно

2024-10-25 12:28 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/mikro-orm-adapter/src/module/mikro-orm-adapter.module.ts
> +      providers: [configProvider, ModuleRef as Provider],
после крайнего мерджа посыпались ошибка в адаптер-модулях:
подключил то, на что были жалобы. к комменту ниже тоже самое
```console
➤ YN0000: │  [Nest] 118259  - 10/25/2024, 3:26:43 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the MikroOrmCoreModule (Symbol(mikro-orm-module-options), 
➤ YN0000: │  ?). Please make sure that the argument ModuleRef at index [1] is available in the MikroOrmCoreModule context.
```

2024-10-25 13:00 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +    const providers = [...serviceProviders, HttpAdapterHost, ModuleRef as Provider]
https://github.com/torin-asakura/shdvor/pull/110#discussion_r1816592055

2024-10-25 13:09 UTC, Nelfimov commented
И да - переведи на fastify бэк

2024-10-25 13:23 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/i18n-adapter/src/module/i18n-adapter.module.ts
> +    const providers = [...serviceProviders, HttpAdapterHost, ModuleRef as Provider]
> нет, модульреф я понял, хотя и большой вопрос. А вот httpadapter вообще непонятно

идентичная ошибка просто. не каких деталей ошибки не вижу, просто просит зависимость в модуль

после мерджа, когда новую ветку создал - 2 адаптера отвалилось

```console
➤ YN0000: │  [Nest] 138789  - 10/25/2024, 4:20:55 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the I18nModule (I18nService, I18nTranslations, 
➤ YN0000: │  I18nOptions, ?). Please make sure that the argument HttpAdapterHost at index [3] is available in the I18nModule context.
➤ YN0000: │  Potential solutions:
➤ YN0000: │  - Is I18nModule a valid NestJS module?
➤ YN0000: │  - If HttpAdapterHost is a provider, is it part of the current I18nModule?
➤ YN0000: │  - If HttpAdapterHost is exported from a separate @Module, is that module imported within I18nModule?
➤ YN0000: │    @Module({
➤ YN0000: │      imports: [ /* the Module containing HttpAdapterHost */ ]
➤ YN0000: │    })
➤ YN0000: │  
➤ YN0000: │  Error: Nest can't resolve dependencies of the I18nModule (I18nService, I18nTranslations, I18nOptions, ?). Please make sure that the argument HttpAdapterHost at
➤ YN0000: │  index [3] is available in the I18nModule context.
➤ YN0000: │  Potential solutions:
➤ YN0000: │  - Is I18nModule a valid NestJS module?
➤ YN0000: │  - If HttpAdapterHost is a provider, is it part of the current I18nModule?
➤ YN0000: │  - If HttpAdapterHost is exported from a separate @Module, is that module imported within I18nModule?
➤ YN0000: │    @Module({
➤ YN0000: │      imports: [ /* the Module containing HttpAdapterHost */ ]
➤ YN0000: │    })
```

2024-10-25 13:25 UTC, kirill-ivanovvv commented
> И да - переведи на fastify бэк

это не оно?

https://github.com/torin-asakura/shdvor/blob/0ed275497e70aeb1f402a0e43aedf62906204956/booking-telegram-bot/entrypoints/service-entrypoint/src/bot-service-entrypoint.bootstrap.ts#L20

2024-10-25 13:26 UTC, Nelfimov commented
ок, вопрос снимается

2024-10-25 13:41 UTC, kirill-ivanovvv commented
@Nelfimov 

адрес разбил на 2 env  - origin:port

const fetchUrl = `${bookingTelegramBotOrigin}:${bookingTelegramBotPort}/booking`

`BOOKING_TELEGRAM_BOT_ORIGIN`
`BOOKING_TELEGRAM_BOT_PORT`

2024-10-28 04:36 UTC, Nelfimov requested changes

2024-10-28 04:36 UTC, Nelfimov commented on site/api/booking/src/booking.api.ts
> +  return fetch(fetchUrl, {
вынеси в отдельную функцию рядом

2024-10-28 04:36 UTC, Nelfimov commented on site/app/src/app/api/booking/route.ts
> +import { bookingApiHandle as POST } from '@site/booking-api'
`export X as Y`

2024-10-28 04:36 UTC, Nelfimov commented on fragments/booking-fragment/src/initial/initial.component.tsx
> +    const jsonData = JSON.stringify({
вынеси в хук или функцию

2024-10-28 04:36 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/controllers/booking.controller.ts
> +      console.error(error)
консоль лог

2024-10-28 04:36 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/controllers/booking.controller.ts
> +      throw new HttpException('Interfnal server error', HttpStatus.INTERNAL_SERVER_ERROR)
если поймал ошибку - может ее надо выводить в новой которую создал?

2024-10-28 04:36 UTC, Nelfimov commented on booking-telegram-bot/contexts/api/infrastructure-module/src/services/booking.service.ts
> +export class BookingService {
должен быть юзкейс - ты же выполняешь какую то логику по эндпоинту

2024-10-28 08:19 UTC, kirill-ivanovvv commented
@Nelfimov сайт недоступен https://shdvor.pro/

2024-10-28 08:42 UTC, Nelfimov requested changes

2024-10-28 08:42 UTC, Nelfimov commented on site/api/booking/src/fetch-telegram-bot-service.helper.ts
> +const fetchTelegramBotHelper: FetchTelegramBotHelperType = async ({ url, data }) =>
такое должно быть в отдельном слое. `data` или `hooks`

2024-10-28 09:36 UTC, Nelfimov approved these changes

2024-10-28 09:36 UTC, merged