Feat/telegram account link
torin-asakura/shdvor pull request #113
Opened 2024-11-01 13:54 UTC by kirill-ivanovvv

2024-11-01 13:55 UTC, kirill-ivanovvv commented
closes https://github.com/torin-asakura/shdvor/issues/112

2024-11-06 14:18 UTC, TorinAsakura commented
> @TorinAsakura ссылки щас на домашние ведут: ![image](https://private-user-images.githubusercontent.com/70315473/383588648-37a6cd9c-676e-40bf-8386-03b1f4243e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDI5NzAsIm5iZiI6MTczMDkwMjY3MCwicGF0aCI6Ii83MDMxNTQ3My8zODM1ODg2NDgtMzdhNmNkOWMtNjc2ZS00MGJmLTgzODYtMDNiMWY0MjQzZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE0MTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjU5NDZiYWE1MjgzMWRjNTMxYzBlOGRjNjczM2ZmYzFhYjZjODYyNTg3ZTc5NzE2ODFkYmNkNDdhYTliNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vnc5vMZULiCkobnl-vczoOBt5WMrWIYYLTr2iFbWcTI)

фейсбук запрещён в стране - его убираем
https://vk.com/shdvor

2024-11-06 15:33 UTC, Nelfimov requested changes

2024-11-06 15:33 UTC, Nelfimov commented on .gitignore
> +..effectivnayarabota1/
лишнее

2024-11-06 15:34 UTC, TorinAsakura commented on .gitignore
> +..effectivnayarabota1/
почистите гитигнор от проекта Мисик

2024-11-06 16:17 UTC, Nelfimov commented on .gitignore
> +..effectivnayarabota1/
см. 74 строку

А сам проект: https://github.com/torin-asakura/misik

2024-11-06 17:36 UTC, Nelfimov approved these changes

2024-11-07 09:29 UTC, merged