Fix: prices
torin-asakura/shdvor pull request #114
Opened 2024-11-01 16:13 UTC by kirill-ivanovvv

closes https://github.com/torin-asakura/shdvor/issues/100

2024-11-03 09:45 UTC, Nelfimov requested changes
не увидел где происходит кэширование

2024-11-03 09:45 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data.getter.ts
> +  const jsonGoodsData: any = await fetchAqsiDataHelper(requestUrl)
`any`

2024-11-03 09:45 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data.getter.ts
> +  const queryPromises: Array<Promise<any>> = [...Array(jsonGoodsData.pages)].map(async (_, index) =>
`any`

2024-11-03 09:45 UTC, Nelfimov commented on globals/data/src/helpers/fetch-aqsi-data.helper.ts
> +  return (await response.json()) as Record<string, any>
а если будет пустое тело в ответе? `.json()` упадет с ошибкой

2024-11-03 09:45 UTC, Nelfimov commented on globals/data/src/helpers/format-aqsi-data.constants.ts
> +const AQSI_REMONT_STALNYH_DISKOV_TITLE = 'Ремонт стальных дисков'
почему кириллица?

2024-11-03 10:59 UTC, kirill-ivanovvv commented on globals/data/src/helpers/format-aqsi-data.constants.ts
> +const AQSI_REMONT_STALNYH_DISKOV_TITLE = 'Ремонт стальных дисков'
сравниваю wp-строки и aqsi-строки
они по некоторым категориям отличаются и в именовании и в падежах
в wp-объект вставлю aqsi-данные, с минимумом изменений. как сделать лучше - не придумал

2024-11-03 11:11 UTC, kirill-ivanovvv commented
> не увидел где происходит кэширование

вообще, запросы с серверной части компонента делаю, поэтому должно кэшироваться. на всех страницах стоит директива `revalidate`:
https://github.com/torin-asakura/shdvor/blob/6ad0271650946f0129680913bf066b3049272049/site/app/src/app/page.ts#L2

можем упаковать этот функционал в api-роут, так бдет чище. и запросы делать также с серверной части компонента через свой апи-роут

1. пребросить все запросы на локальный роут
2. на локальный роут перенести всю логику с получением данных через aqsi
3. повесить на `fetch` опцию `revalidate` - https://nextjs.org/docs/14/app/building-your-application/data-fetching/fetching-caching-and-revalidating#time-based-revalidation

@Nelfimov будем делать? сегодня не успею, но заавтра с утра закончу

2024-11-03 12:19 UTC, Nelfimov commented on globals/data/src/helpers/format-aqsi-data.constants.ts
> +const AQSI_REMONT_STALNYH_DISKOV_TITLE = 'Ремонт стальных дисков'
Посмотри - возможно из вп можно вытащить не название а ID либо латиницу

2024-11-03 13:05 UTC, Nelfimov commented
> можем упаковать этот функционал в api-роут, так бдет чище. и запросы делать также с серверной части компонента через свой апи-роут
> 
> 
> 
> 1. пребросить все запросы на локальный роут
> 
> 2. на локальный роут перенести всю логику с получением данных через aqsi
> 
> 3. повесить на `fetch` опцию `revalidate` - https://nextjs.org/docs/14/app/building-your-application/data-fetching/fetching-caching-and-revalidating#time-based-revalidation
> 
> 
> 
> @Nelfimov будем делать? сегодня не успею, но заавтра с утра закончу

Я как раз этот способ и подразумевал. Давай сделаем.

2024-11-04 15:12 UTC, kirill-ivanovvv commented on globals/data/src/helpers/format-aqsi-data.constants.ts
> +const AQSI_REMONT_STALNYH_DISKOV_TITLE = 'Ремонт стальных дисков'
- `services` можно сравнивать по `url из wordpress` и `group_id из aqsi`
- car-bodies всеравно останется кириллицей, к ним ничего не привязанно

2024-11-04 15:16 UTC, kirill-ivanovvv commented
> > можем упаковать этот функционал в api-роут, так бдет чище. и запросы делать также с серверной части компонента через свой апи-роут
> > 
> > 1. пребросить все запросы на локальный роут
> > 2. на локальный роут перенести всю логику с получением данных через aqsi
> > 3. повесить на `fetch` опцию `revalidate` - https://nextjs.org/docs/14/app/building-your-application/data-fetching/fetching-caching-and-revalidating#time-based-revalidation
> > 
> > @Nelfimov будем делать? сегодня не успею, но заавтра с утра закончу
> 
> Я как раз этот способ и подразумевал. Давай сделаем.

- не могу сделать запрос на текущий адресс, не зная `origin сервера`
- пробовал получить его в серверной функции через `headers` - возрвращает `null`
- на `fetch` повесли `revalidate`, немного переупаковал функционал, должно нормально кешировать.

2024-11-04 16:32 UTC, Nelfimov commented
Сайт крутится на shdvor.pro

2024-11-05 07:24 UTC, kirill-ivanovvv commented
> Сайт крутится на shdvor.pro

это понимаю. просто в константу зашить?

2024-11-05 07:31 UTC, Nelfimov commented
> > Сайт крутится на shdvor.pro
> 
> это понимаю. просто в константу зашить?

Переменную окружения конечно

2024-11-05 07:31 UTC, Nelfimov commented
c фоллбэком

2024-11-05 12:25 UTC, kirill-ivanovvv commented
<details>
<summary>старые цены</summary>

![image](https://github.com/user-attachments/assets/37f15a31-53cb-424e-9e95-1617f95103e9)
![image](https://github.com/user-attachments/assets/d2c7e9e4-fa81-491a-881c-a75ee5f89d16)

</details>

<details>
<summary>новые цены</summary>

![image](https://github.com/user-attachments/assets/f7d1fac7-152e-42ca-b6af-c77fbd368567)
![image](https://github.com/user-attachments/assets/4ec0d58c-7bc4-4110-a021-ed3482a2732c)

</details>

---

@Nelfimov, нужно еще вот этот пункт поправить - https://github.com/torin-asakura/shdvor/pull/114#discussion_r1827897526

- щас на вп зашел, можно в поле с конетентом добавить латиницу, и по ней сравнивать (в консоли поле content)
![image](https://github.com/user-attachments/assets/39fc5621-25bf-4e3e-aa48-11bc9c843de0)
![image](https://github.com/user-attachments/assets/43f3f0eb-ccfc-49b1-b24a-71d82c0c223d)

2024-11-06 06:31 UTC, kirill-ivanovvv commented
> Завтра с утра проведу ревью.
> 
> Пока проверь что те переменные окружения которые ты добавил, и которые используются в других приложениях, имеют одинаковый нейминг

2 переменные добавил:
1. ` process.env.SITE_ORIGIN` - новая, фоллбэк - `https://shdvor.pro`
2. `process.env.API_KEY` - была, название сохранил. для доступа к aqsi

2024-11-06 06:40 UTC, Nelfimov requested changes
на кириллицу повесь `TODO`

2024-11-06 06:40 UTC, Nelfimov commented on .gitignore
> +..effectivnayarabota1/
уверен что это надо? так то директория вне проекта. Если тебе пришлось тем более что то личное добавлять в гитигнор - что то пошло не так

2024-11-06 06:40 UTC, Nelfimov commented on site/pages/index-page/src/hooks/run-index-page-server-queries.hook.ts
> +
промисы выше добавь в `Promise.allSettled`

2024-11-06 06:40 UTC, Nelfimov commented on site/pages/index-page/src/index-page.client.tsx
> +  const replacedServicePrices = replaceServicePricesHelper(services, aqsiServicesData)
когда перейдем - это уже не будет `replaced`

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-from-local-route-getter/aqsi-data-from-local-route.getter.ts
> +    const fetchUrl = new URL(API_ROUTE, baseUrl)
а нужно ли так указывать? Мне казалось можно тупо указать `/api/aqsi-data` и некст поймет что нужно на себя делать запрос

2024-11-06 06:40 UTC, Nelfimov commented on site/app/src/app/api/aqsi-data/route.ts
> +export { aqsiDataApiHandle as GET } from '@site/aqsi-data-api'
давай в нейминге не привязываться к поставщику данных - потом будет не акси а яндекс

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/format-output-data-helper/format-output-data.helper.ts
> +    } else if (itemRadiiTitle && !itemCarBodyTitle) {
посмотри можно ли избавиться от `else`

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/format-pages-data-helper/format-pages-data.helper.ts
> +    if (!pageData) throw new Error('data not exitst on page-response')
создай отдельный класс ошибки

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/format-pages-data-helper/format-pages-data.helper.ts
> +    const pageData = await pageResponse.json()
`.json()` упадет если тело ответа пустое. Попробуй сначала перевести в текст `.text()`, затем если он не пустой, то спарсить `JSON.parse()`

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/awsi-data.constants.ts
> +export const AQSI_API_URL = 'https://api.aqsi.ru/pub/v2'
это я могу в проде передать через переменные окружения

2024-11-06 06:40 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/awsi-data.constants.ts
> +export const AQSI_API_URL = 'https://api.aqsi.ru/pub/v2'
обязательно добавь фоллбэк

2024-11-06 07:02 UTC, kirill-ivanovvv commented on globals/data/src/getters/aqsi-data-from-local-route-getter/aqsi-data-from-local-route.getter.ts
> +    const fetchUrl = new URL(API_ROUTE, baseUrl)
вот об этом и говорил.
- пробовал делать так - не работало
- пробовал через `next/headers` получить доступ к текущему `url`-

2024-11-06 07:13 UTC, Nelfimov commented
Мы похоже пошли не тем путем 

![image](https://github.com/user-attachments/assets/073ad585-2872-4986-915e-c87f52ab443b)

2024-11-06 16:18 UTC, kirill-ivanovvv commented on globals/data/src/getters/aqsi-data-getter/format-pages-data-helper/format-pages-data.helper.ts
> +      const pageData = await JSON.parse(responseText)
> разве здесь `await` нужен?

pageResponse.text() - промис, еслинт не даеет убрать await у лупа

2024-11-06 16:19 UTC, Nelfimov commented on globals/data/src/getters/aqsi-data-getter/format-pages-data-helper/format-pages-data.helper.ts
> +      const pageData = await JSON.parse(responseText)
я про `JSON.parse`

2024-11-06 17:35 UTC, Nelfimov approved these changes

2024-11-06 17:36 UTC, merged