Feat/2gis feed
torin-asakura/shdvor pull request #129
Opened 2024-11-25 16:01 UTC by kirill-ivanovvv

closes https://github.com/torin-asakura/shdvor/issues/124

2024-11-26 12:10 UTC, TorinAsakura requested changes
1. Содержимое "форматтера" относится к доменному слою так как реализует бизнес-логику
2. Сам же форматтер является элементарным адаптером
3. Убрать игноры для тс/линта

2024-11-27 06:36 UTC, kirill-ivanovvv commented
@Nelfimov я же правильно понял, что нужно побить один пакет-ентрипоинт на nest-модули?

получить данные
обработать
отправить

---

- адаптер для получения данных - фетч
- адаптер клиента s3

---

- модуль инфраструктуры, который связывает адаптеры и application-юс-кейсы в ports
- в этом модуле будет вызываться последовательность юс-кейсов

---

- юс-кейс для получения данных (связывается через инфрастуктуру с фетч-адаптером)
- юс-кейс для форматирования их в формат xml (логика форматирования будет в одной директории с этим юс-кейсом)
- юс-кейс для отправки (связывается через инфрастуктуру с с3-адаптером)

**не понимаю, как:**
- повесить крон. по логике - на уровне инфраструктуры, но как это должно выглядеть в коде. если есть примеры, скинь пожалуйста
- какой выделить контекст для основной инфраструктуры, из которой будет вызываться последовательность юс-кейсов. 
- какой выделить контекст для форматирования xml
- на счет доменного слоя не понял. вчера смотрел примеры в дельте и migration-bot, пытался собрать. не понимаю что у нас может быть `factory` и что у нас может быть `aggregates`

---

- у нас в итоге должен получиться скрипт, который выполняется при запуски и при вызове крона

2024-11-27 06:43 UTC, Nelfimov commented
> * адаптер для получения данных - фетч

`undici`

> * адаптер клиента s3

Адаптер будет называться `storage-adapter

> * модуль инфраструктуры, который связывает адаптеры и application-юс-кейсы в ports

- юз кейс (app) использует адаптер через порт (app), которого есть имплементация (infr)
- юз кейс (app) вызывается через processor (infr)

> * в этом модуле будет вызываться последовательность юс-кейсов
> 
> * юс-кейс для получения данных (связывается через инфрастуктуру с фетч-адаптером)
> * юс-кейс для форматирования их в формат xml (логика форматирования будет в одной директории с этим юс-кейсом)
> * юс-кейс для отправки (связывается через инфрастуктуру с с3-адаптером)

- один юзкейс - получение и обработка данных для яндекса
- один юзкейс - получени и обработка данных для 2гис

> **не понимаю, как:**
> 
> * повесить крон. по логике - на уровне инфраструктуры, но как это должно выглядеть в коде. если есть примеры, скинь пожалуйста

повесишь на processor (infr)
`cron` - тоже адаптер

> * какой выделить контекст для основной инфраструктуры, из которой будет вызываться последовательность юс-кейсов.

`prices`

> * какой выделить контекст для форматирования xml

`prices`

> * на счет доменного слоя не понял. вчера смотрел примеры в дельте и migration-bot, пытался собрать. не понимаю что у нас может быть `factory` и что у нас может быть `aggregates`
> 
> * у нас в итоге должен получиться скрипт, который выполняется при запуски и при вызове крона

В рамках этой задачи сделай функционал "шоб работало" - выпустим его. А следом делай таску на рефактор

2024-11-27 07:56 UTC, kirill-ivanovvv commented
@Nelfimov

- можно ли вызывать в рамках одного контекста, на уровне инфраструктуры, юс-кейсы другого контекста?
- в боте я вызываю юс-кейсы другого контекста только на уровне application

инфраструктура-сервиса-1 -> юс-кейс-сервиса-2
**ИЛИ**
инфраструктура-сервиса-1 -> юс-кейс-сервиса-1 -> юс-кейс-сервиса-2

2024-11-27 08:29 UTC, Nelfimov commented
ну и опять же - в рамках этой задачи не вижу как у тебя будет два контекста. Тут один - `prices`

2024-11-27 13:27 UTC, kirill-ivanovvv commented
- есть ошибки при коммите, поэтому коммичусь --no-verify (см лог в конце сообщения)
- все ошибки ts, что нашел при помощи yarn check - закрыл
- ошибки линтера сыпятся по всему приложению, их много, поэтому их оставляю, таска на линт висит. (насколько понимаю, после обновления бандла изменился конфиг)
- в prices/entrypoint/src/result в дев-режиме пишется xml. новый соответствует требованиям, старый без изменений
- функцинал отправки на бакет упаковал в storage-adapter. его не менял, но и не тестировал.
- 2gis-xml будет сохранен под следующими именами - `two-gis-prices-${dateString}.xml`, `two-gis-prices-latest.xml`
- крон проверил

<details>
<summary>log</summary>

```console
[operator@archlinux atls_shdvor]$ git commit -m "refactor(prices): nest"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ Config object — 52 files
    ✔ *.{yml,yaml,json,graphql,md} — 6 files
    ❯ *.{js,mjs,cjs,jsx,ts,tsx} — 45 files
      ✖ yarn format
      ◼ yarn lint
    ❯ *.{ts,tsx} — 44 files
      ✖ yarn typecheck
    ❯ *.{tsx,ts} — 44 files
      ✖ yarn test unit [FAILED]
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ yarn test unit:
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                              │
│  ENAMETOOLONG: name too long, stat                                                                                                                           │
│  '/home/operator/work/atls_shdvor/**/!(integration)/*/home/operator/work/atls_shdvor/globals/config/src/constants/prices-required-envs.constants.ts          │
│  /home/operator/work/atls_shdvor/globals/data/src/error/goods-category-data-validation.error.ts                                                              │
│  /home/operator/work/atls_shdvor/globals/data/src/error/goods-data-validation.error.ts /home/operator/work/atls_shdvor/globals/data/src/error/index.ts       │
│  /home/operator/work/atls_shdvor/globals/data/src/index.ts /home/operator/work/atls_shdvor/globals/data/src/interfaces/goods-category-data.interface.ts      │
│  /home/operator/work/atls_shdvor/globals/data/src/interfaces/goods-data.interface.ts /home/operator/work/atls_shdvor/globals/data/src/interfaces/index.ts    │
│  /home/operator/work/atls_shdvor/globals/data/src/validators/goods-category-data.validator.ts                                                                │
│  /home/operator/work/atls_shdvor/globals/data/src/validators/goods-data.validator.ts /home/operator/work/atls_shdvor/globals/data/src/validators/index.ts    │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/errors/index.ts                                                                         │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/errors/put-object-to-s3.error.ts                                                        │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/index.ts                                                                                │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/module/index.ts                                                                         │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/module/storage-adapter.module.ts                                                        │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/services/index.ts                                                                       │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/services/put-object-to-s3.service.ts                                                    │
│  /home/operator/work/atls_shdvor/prices/adapters/storage-adapter/src/services/s3-adapter.service.ts                                                          │
│  /home/operator/work/atls_shdvor/prices/adapters/undici-adapter/src/errors/index.ts                                                                          │
│  /home/operator/work/atls_shdvor/prices/adapters/undici-adapter/src/module/undici-adapter.module.ts                                                          │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/interfaces/index.ts                                                           │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/interfaces/query-data.interface.ts                                            │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/module/prices-application.module.ts                                           │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/ports/index.ts                                                                │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/ports/query-client.port.ts                                                    │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/ports/storage.port.ts                                                         │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/use-cases/get-2gis-prices-xml.use-case.ts                                     │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/use-cases/get-query-data.use-case.ts                                          │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/use-cases/get-yandex-prices-xml.use-case.ts                                   │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/use-cases/index.ts                                                            │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/application-module/src/use-cases/put-object-to-s3.use-case.ts                                        │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/getters/cron-task.getter.ts                                                │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/getters/index.ts                                                           │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/interfaces/goods-category-data.interface.ts                                │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/interfaces/goods-data.interface.ts                                         │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/interfaces/index.ts                                                        │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/module/prices-infrastructure.module.ts                                     │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/module/prices-infrastructure.providers.ts                                  │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/ports/index.ts                                                             │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/ports/query-client.port.ts                                                 │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/ports/storage.port.ts                                                      │
│  /home/operator/work/atls_shdvor/prices/contexts/prices/infrastructure-module/src/processors/prices.processor.ts                                             │
│  /home/ [...]

2024-11-27 15:14 UTC, Nelfimov requested changes
1. сообщения в эксепшенах - приведи в норму, за пример можешь взять https://github.com/delta-doc/web/tree/master/documents/core/domain-module/src/exceptions
2. не так меня понял по поводу `undici` - это просто библиотека которой стоит пользоваться для фетчинга данных. Сам адаптер будет скорее `fetcher-adapter`. Ну и перезрузил его логикой - адаптер лишь дает возможность с чем то работать. В твоем случае куда и какие запросы делать может знать инфра

2024-11-27 15:14 UTC, Nelfimov commented on prices/entrypoints/service-entrypoint/src/prices-service-entrypoint.bootstrap.ts
> +  await app.listen(process.env.BOOKING_TELEGRAM_BOT_PORT || 3000)
тут нужно указывать `0.0.0.0` чтобы был доступ вне контейнера. Проверь

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/application-module/src/use-cases/index.ts
> +export * from './put-object-to-s3.use-case.js'
много юзкейсов. У тебя все два - яндекс и 2гис

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/application-module/src/ports/query-client.port.ts
> +export abstract class QueryClientPort {
скорее `FetchClient`

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/getters/cron-task.getter.ts
> +import { CronJob }     from 'cron'
у неста есть библиотека по работе с кроном, работает через декораторы. Бери ее

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/getters/cron-task.getter.ts
> +import { CronJob }     from 'cron'
ну и это не должно быть в `getters`

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/processors/prices.processor.ts
> +  async onModuleInit(): Promise<void> {
это не нужно будет когда начнешь пользоваться кроном неста

2024-11-27 15:14 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/processors/prices.processor.ts
> +    const twoGisXml = await this.get2gisPricesXmlUseCase.execute(queryData)
юзкейсы сами должны всю логику положить. У тебя бизнес задача:
1. получить цены с источника
2. преобразовать их к определенному виду
3. сохранить в бакет

Вот все выше перечисленное должно быть в юз кейсе

2024-11-28 07:41 UTC, kirill-ivanovvv commented on prices/contexts/prices/application-module/src/use-cases/index.ts
> +export * from './put-object-to-s3.use-case.js'
получение данных общее для обоих сервисов. вынесу это в отдельный юскейс?

2024-11-28 08:28 UTC, Nelfimov commented on prices/contexts/prices/application-module/src/use-cases/index.ts
> +export * from './put-object-to-s3.use-case.js'
можешь в отдельный сервис вынести в `application`

2024-11-28 12:39 UTC, Nelfimov commented on prices/adapters/fetcher-adapter/src/exceptions/exceptions.constants.ts
> +  RESPONSE_IS_NULL = 'Respose is nullish',
очепятка

2024-11-28 12:39 UTC, Nelfimov commented on prices/adapters/fetcher-adapter/src/module/undici-adapter.module.ts
> +export class FetcherAdapterModule {
файл называется по одному, а класс - по другому

2024-11-28 12:41 UTC, Nelfimov commented on prices/adapters/fetcher-adapter/src/services/fetch.service.ts
> +      headers: {
ты ведь можешь заголовки передавать в аргументах. А так же тело для запроса.

А вообще такое легче сделать через отдельные методы, например:

```ts
async get(url, body, headers) {}

async post(url, body, headers) {}

async put(url, body, headers) {}
```

2024-11-28 12:41 UTC, Nelfimov commented on prices/adapters/fetcher-adapter/src/services/fetch.service.ts
> +      logger.info(`successful fetching: ${url}`)
это скорее уровень дебага

2024-11-28 12:42 UTC, Nelfimov commented on prices/adapters/fetcher-adapter/package.json
> +    "cron": "3.1.7",
cron тут как будто не нужен

2024-11-28 12:43 UTC, Nelfimov commented on prices/adapters/storage-adapter/src/services/put-object-to-s3.service.ts
> +export class PutObjectToS3Service {
можно так а можно один сервис с множеством методов. Это больше для инфо, а не для правок

2024-11-28 12:46 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/processors/prices.processor.ts
> +  @Cron('0 0 * * 0')
вынеси строку в константу с хорошим неймингом

2024-11-28 13:58 UTC, kirill-ivanovvv commented on prices/adapters/fetcher-adapter/src/exceptions/empty-yandex-data.exception.ts
> +export class EmptyYandexDataError extends Error {
неиспользуется, убрал

2024-11-29 06:28 UTC, Nelfimov approved these changes
по оставшимся замечаниям делай таски на рефактор

2024-11-29 06:28 UTC, Nelfimov commented on prices/contexts/prices/infrastructure-module/src/constants/update-prices-cron.constants.ts
> +export const UPDATE_PRICES_CRON = '0 0 * * 0'
обычно пишут что здесь подразумевается. Напр `CRON_EVERY_DAY`. Это на будущее

2024-11-29 06:28 UTC, Nelfimov commented on prices/contexts/prices/application-module/src/mappers/index.ts
> +export * from './yandex-offers.mapper.js'
все эти штуки я бы попробовал скомпоновать в два сервиса с множеством методов

2024-11-29 06:28 UTC, Nelfimov commented on prices/contexts/prices/application-module/src/services/get-query-data.service.ts
> +export class GetQueryDataService {
нейминг - непонятный `Query`

2024-11-29 06:28 UTC, merged