feat: init data layer
torin-asakura/shdvor pull request #17
Opened 2022-07-07 14:33 UTC by brusselboy

2022-07-07 14:39 UTC, TFK70 requested changes

2022-07-07 14:39 UTC, TFK70 commented on fragments/articles-fragment/src/data/queries/posts/posts.interface.ts
> +  __typename: string
Не советую перенимать на клиентскую часть все погрешности схемы на вордпрессе, тебе на клиенте __typename нигде не пригодится, так что можешь его просто игнорировать

2022-07-11 17:37 UTC, TFK70 requested changes

2022-07-11 17:37 UTC, TFK70 commented on fragments/articles-fragment/src/article/article.component.tsx
> +import DOMPurify           from 'dompurify'
Немного не догоняю зачем он тебе

2022-07-11 17:37 UTC, TFK70 commented on fragments/articles-fragment/src/messages/messages.ts
> +    views: 'просмотров',
plural не вывозит?

2022-07-11 17:37 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +  const titles = {
https://t.me/atls_lab/528

2022-07-11 17:37 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +    titles.titleBottom = infographics[0]?.title
Очень ненадёжно и неявно сделано, номерной индекс в данном случае не лучший выбор для идентификатора

2022-07-11 17:37 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +    titles.titleBottom = infographics[0]?.title
Опиши в общих чертах ситуацию, чтобы понять почему так сделано

2022-07-12 07:46 UTC, brusselboy commented on fragments/articles-fragment/src/article/article.component.tsx
> +import DOMPurify           from 'dompurify'
так как я использую [dangerouslySetInnerHTML](https://github.com/torin-asakura/shdvor/blob/feat/data/fragments/articles-fragment/src/article/article.component.tsx#L103) рекомендуется вместе с ним использовать dompurify для надежности, потому что dangerouslySetInnerHTML не безопасный, а dompurify очищает html и предотвращает xss

2022-07-12 07:47 UTC, brusselboy commented on fragments/articles-fragment/src/messages/messages.ts
> +    views: 'просмотров',
он так и работает, ему нужно в трёх склонениях слово передавать

2022-07-12 07:47 UTC, brusselboy commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +    titles.titleBottom = infographics[0]?.title
согласен, если на бекенде добавить еще один айтем, тогда у всех элементов поменяется индекс, т.к новый элемент добавляется в начало, что ещё в данном случае можно использовать для идентификатора?

2022-07-12 08:22 UTC, TorinAsakura commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +    titles.titleBottom = infographics[0]?.title
> согласен, если на бекенде добавить еще один айтем, тогда у всех элементов поменяется индекс, т.к новый элемент добавляется в начало, что ещё в данном случае можно использовать для идентификатора?

вероятно, непосредственный id, если таковой имеется

2022-07-12 14:10 UTC, TFK70 commented on fragments/articles-fragment/src/article/article.component.tsx
> +import DOMPurify           from 'dompurify'
А зачем ты dangerouslySetInnerHTML юзаешь?

2022-07-12 14:14 UTC, TFK70 requested changes

2022-07-12 14:42 UTC, brusselboy commented on site/hero-fragment/src/hero.component.tsx
> +              {title.text?.substring(0, title.text.lastIndexOf(' '))}
вырезает последнее слово

2022-07-13 17:04 UTC, brusselboy commented on fragments/articles-fragment/src/article/article.component.tsx
> +import DOMPurify           from 'dompurify'
> А зачем ты dangerouslySetInnerHTML юзаешь?

Перепробовал разные парсеры для реакта, но с ними появляется проблема с зависимостями, но по сути что эти парсеры, что dangerouslySetInnerHTML все делают одно и тоже, по-этому, раз реакт предоставляет из коробки парсер, решил остановиться на dangerouslySetInnerHTML, почитал про него и как вот выше написал, рекомендуют использовать dompurify. 

Если же dangerouslySetInnerHTML нам никак не подходит, можно сделать через какой-нибудь парсер, просто сделал так из-за того, что результат одинаковый

2022-07-13 17:04 UTC, brusselboy commented on site/hero-fragment/src/hero.component.tsx
> +    CTA = extractor(hero, 'id', 'cG9zdDoyMDAy')
Исправил

2022-07-13 17:48 UTC, TFK70 commented on fragments/articles-fragment/src/article/article.component.tsx
> +import DOMPurify           from 'dompurify'
@brusselboy все, допёр зачем это, не сразу врубился что это записи из блога, сори
Тогда все хорошо, оставь так

2022-10-10 17:32 UTC, TFK70 requested changes
1. Ширина хиро должна быть 1280px
![image](https://user-images.githubusercontent.com/62806448/194921489-6bdd56ea-5ff6-4eb9-823c-8f916c329412.png)

2. С блоком "Наши услуги" (и со всеми остальными) аналогично: у него ширина меньше 1440 пикселей, в дизайне 1440px - это вьюпорт, а не ширина самого блока

![image](https://user-images.githubusercontent.com/62806448/194921786-51e5a9e9-dbde-4266-be80-7a0cb203bf11.png)

3. У текста в кнопках выбора радиуса другой fontWeight

![image](https://user-images.githubusercontent.com/62806448/194921985-2cb773e0-87a4-46fa-b5cc-fb22b7479b63.png)

4. Линк в хедере на блог ведёт на роут "блог", а должен вести на домен с блогом. Домен с блогом должен браться из енва: process.env.BLOG_URL

Остальные блоки тоже сверь на pixel perfect

2022-10-11 20:39 UTC, TFK70 requested changes
1. Плашка с выбором радиуса ведёт себя странно как-то. Я так понимаю она должна иметь position fixed, и быть по центру:

![image](https://user-images.githubusercontent.com/62806448/195193551-cefcf177-a88c-49e2-ba2c-bf577de24408.png)

2. И в дополнение к ласт скрину: контент должен быть центрирован, щас он к левому краю прикреплен

2022-10-14 14:04 UTC, TFK70 requested changes

2022-10-14 14:04 UTC, TFK70 commented on ui/button/package.json
> +    "@atls-ui-generators/button": "0.0.10",
Еще добавь в этот пекедж скрипт который будет отвечать за генерацию, чтобы каждый раз по-новой не приходилось в команду пути прописывать из корня

2022-10-14 16:03 UTC, TFK70 requested changes
1. Форме со страницы `/services` нужно выставить фиксированные пиксели из дизайна

<details>

![image](https://user-images.githubusercontent.com/62806448/195889924-d66b1838-7c56-48cf-b0e1-8143274b9da4.png)

</details>

2. В блоге кнопка "Записаться" в навигейшне ведёт на не существующий роут
3. Почему вообще "Записаться" - это отдельная страница? Это ведь типа модалка, но она вообще всё пространство собой закрывает, это же не страница
4. У тебя настроена интеграция с ninja forms на вордпрессе? После отправки заявки письмо на почту отправляется?
5. Ни у одной страницы нет SEO каркаса
6. Нет опенграфа
7. Нет сайтмапа (https://github.com/atls/nextjs/tree/master/packages/next-sitemap-generator)

2022-10-17 16:51 UTC, TFK70 approved these changes

2022-10-17 23:36 UTC, TorinAsakura requested changes

2022-10-17 23:36 UTC, TorinAsakura commented on globals/data/src/data/queries/services.query.ts
> +            r12
Это слишком узко, что есть там добавится или, наоборот, сократится набор радиусов? Заверни в переменную или вайлдкард используй.
А то сейчас возникнет дилемма 250-й страницы…
@TFK70  fyi

2022-10-17 23:36 UTC, TorinAsakura commented on site/fragments/articles-fragment/src/messages/messages.ts
> +    view: 'просмотр',
разучились пользоваться интлом? эт чо такое? @TFK70

2022-10-18 18:24 UTC, TFK70 approved these changes

2022-10-18 19:38 UTC, TorinAsakura requested changes

2022-10-18 19:38 UTC, TorinAsakura commented on site/fragments/services-fragment/src/services-list/service/service.interface.ts
> +    r21: number
при всём при этом, меня беспокоит вопрос - а где же минивены, джипы и прочие "овер-радиусы"?

2022-10-18 19:38 UTC, TorinAsakura commented on site/pages/index-page/src/queries/seo.query.ts
> +    pageBy(uri: "/home") {
может лучше получать страниц по настройкам ВП? урл, название, айди может изменится

2022-10-21 08:33 UTC, carminio commented on site/fragments/hero-fragment/src/hero.component.tsx
> +  const linkFb = contactsObj?.linkFb
Да, они используются и в контактах и в футере, я из компонента страницы передаю дату (в данном случае дата с контактами) в компоненты и в них уже ее деструктуризирую

2022-10-21 08:41 UTC, TFK70 commented on site/pages/index-page/src/queries/seo.query.ts
> +    pageBy(uri: "/home") {
Согласен, для удобства собрал все поля которые можно в теории использовать как идентификатор у страницы, uri вполне сойдёт:

```json
[
        {
          "slug": "services",
          "title": "Услуги",
          "pageId": 2296,
          "link": "https://wp.shdvor.pro/services/",
          "id": "cG9zdDoyMjk2",
          "guid": "https://wp.shdvor.pro/?page_id=2296",
          "uri": "/services/"
        },
        {
          "slug": "blog",
          "title": "Блог",
          "pageId": 2050,
          "link": "https://wp.shdvor.pro/blog/",
          "id": "cG9zdDoyMDUw",
          "guid": "https://wp.shdvor.pro/?page_id=2050",
          "uri": "/blog/"
        },
]
```

2022-10-25 16:50 UTC, TFK70 approved these changes

2022-10-25 21:41 UTC, TorinAsakura approved these changes

2022-10-25 21:41 UTC, merged