fix: layout, styles
torin-asakura/shdvor pull request #32
Opened 2022-10-28 14:30 UTC by carminio

2022-10-28 18:11 UTC, TFK70 commented
@carminio все-равно при переходах по страницам есть дилей на секунду+

Нужна какая-то реактивность в интерфейсе, а то как в вк прямо - на кнопку нажал и не знаешь нажал ли ты на неё вообще

Во-первых, нужно добавить линкам active state, тот который появляется только на момент клика по ссылке
Во-вторых, если дилей все-таки не получится уменьшить до приемлемого времени - нужна заглушка/прелоадер

2022-11-01 09:41 UTC, TFK70 requested changes
Чет active state у линков работает как-то странно. Он должен появляться только на момент клика, а он у тебя держится пока страница не перезагрузится. Я же говорил про обычный active стейт как `:active` псевдокласс в css

И вообще у линков есть ещё и ховер стейт - https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=468%3A1147

И на главной странице в хедере изменений особо нет, ты видимо забыл отдельно его обновить

2022-11-08 09:01 UTC, TFK70 requested changes
Вообще получилось круто, возможно стоит вынести этот прогресс в uikit

2022-11-08 09:01 UTC, TFK70 commented on blog/app/src/pages/_app.tsx
> +  color: '#4579ff',
Это лучше брать из темы

2022-11-08 09:01 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +      .bar-of-progress {
Это лучше тоже поместить в ui, это можно сделать через `injectGlobal` (`@emotion/css`)

2022-11-08 09:42 UTC, carminio commented on ui/theme/src/global.styles.tsx
> +      .bar-of-progress {
> Это лучше тоже поместить в ui, это можно сделать через `injectGlobal` (`@emotion/css`)

оно же и так в ui в injectGlobal

2022-11-08 10:59 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +      .bar-of-progress {
Ну я имею в виду чтобы это находилось в `ui/progress`, а не в `ui/theme`. Ты можешь делать инжект глобал не только в theme

2022-11-08 11:00 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +      .bar-of-progress {
Пример - https://github.com/atls/uikit/blob/master/ui-parts/swiper/src/swiper.tsx#L20

2022-11-08 13:13 UTC, TFK70 approved these changes

2022-11-11 20:39 UTC, TorinAsakura approved these changes

2022-11-11 20:40 UTC, merged