feat: price management
torin-asakura/shdvor pull request #39
Opened 2022-11-23 15:53 UTC by carminio

2022-11-23 16:00 UTC, TFK70 requested changes

2022-11-23 16:00 UTC, TFK70 commented on core/service-prices/src/servicePrices.ts
> +dotenv.config()
Ваще никогда не используй dotenv, у тебя есть докер для этого

Сделай `docker-compose.yml` по аналогии с другими проектами, заверни туда свой сервис и добавь энв

2022-11-23 18:17 UTC, TFK70 requested changes

2022-11-23 18:17 UTC, TFK70 commented on prices/service-entrypoint/src/servicePrices.ts
> +    console.log('Goods data written successfully')
Предполагается что сервис будет работать в режиме daaemon/демон (тоже погугли), а не использоваться разово
Поэтому используй `@atls/logger` либу:

```typescript
const logger = new Logger('Prices')

logger.info('string')
```

2022-11-23 18:17 UTC, TFK70 commented on prices/service-entrypoint/src/servicePrices.ts
> +task.start()
Также, в дополнение к предыдущему комменту: ты уверен, что твой скрипт исполняется "вечно"? А не прекращает своё исполнение после определённого момента?

Если нет - можешь заюзать для этого [forever](https://github.com/foreversd/forever)

2022-11-23 18:17 UTC, TFK70 commented on prices/service-entrypoint/src/servicePrices.ts
> +export { servicePrices }
И раз этот файл у тебя единственный модуль - зачем это куда-то экспортить?

2022-11-23 18:17 UTC, TFK70 commented on prices/service-entrypoint/src/servicePrices.ts
> +export { servicePrices }
Сделай так же файл [bootstrap](https://github.com/atls/orbitto/blob/master/public-gateway/entrypoints/public/src/bootstrap.ts)

2022-11-28 16:31 UTC, TFK70 requested changes

2022-11-28 16:31 UTC, TFK70 commented on prices/service-entrypoint/src/generator/generate-xml.ts
> +  const xmlFile = `<?xml version="1.0" encoding="UTF-8"?>
втф)
Используй либу [типа такой](https://www.npmjs.com/package/xml-js), чтобы генерить xml из json

2022-11-28 16:31 UTC, TFK70 commented on prices/service-entrypoint/src/http/constants.ts
> +export const API_URL = 'https://api.aqsi.ru/pub/v2/'
Такие вещи нужно выносить в энв

2022-11-28 16:31 UTC, TFK70 commented on prices/service-entrypoint/src/http/constants.ts
> +export const GOODS_LIST = 'Goods/list'
Это path, я так понимаю. Это должно быть отражено в названии переменной, и path всегда начинается со `/` (`/Goods/List`)

2022-11-28 16:31 UTC, TFK70 commented on prices/service-entrypoint/src/utils/pretty.util.ts
> +import * as prettierPlugin from '@atls/prettier-plugin'
Зачем это тебе?

2022-11-29 08:21 UTC, carminio commented on prices/service-entrypoint/src/generator/generate-xml.ts
> +  const xmlFile = `<?xml version="1.0" encoding="UTF-8"?>
> втф) Используй либу [типа такой](https://www.npmjs.com/package/xml-js), чтобы генерить xml из json

я не генерю xml из json, в json`ах у меня находятся только данные, по которым я итерируюсь, эту либу удобно было бы заюзать как раз если из такого вида как у меня, если нужно было бы сообразить json формат, но не для генерации xml

2022-11-29 09:25 UTC, TFK70 commented on prices/service-entrypoint/src/generator/generate-xml.ts
> +  const xmlFile = `<?xml version="1.0" encoding="UTF-8"?>
Ничего не понял, эта либа буквально генерит xml на основе json, ты с xml форматом вообще не работаешь

2022-11-29 09:26 UTC, TFK70 requested changes

2022-11-29 09:26 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
> +  const goodsCategoryResponse = await fetchData(`${process.env.API_URL}${GOODS_CATEGORY}`)
Нет, верни переменную в constants, просто присвой ей значение из энва там

Если у тебя название переменной изменится - то жопа

2022-11-29 09:26 UTC, TFK70 commented on prices/service-entrypoint/src/http/constants.ts
> +export const GOODS_CATEGORY = '/GoodsCategory/list'
PATH  в названии еще добавь

2022-11-29 09:26 UTC, TFK70 commented on prices/service-entrypoint/src/utils/pretty.util.ts
>  const pretty = (string: string): string =>
Ты мне так и не ответил зачем тебе это

2022-11-29 09:29 UTC, carminio commented on prices/service-entrypoint/src/utils/pretty.util.ts
>  const pretty = (string: string): string =>
> Ты мне так и не ответил зачем тебе это

ты просто указал на импорт, думал он не нужен, [тут](https://github.com/torin-asakura/shdvor/blob/feat/price-management/prices/service-entrypoint/src/bootstrap.ts#L61) использую, офк можно и без него обойтись

2022-11-29 09:39 UTC, TFK70 commented on prices/service-entrypoint/src/generator/generate-xml.ts
> +  const xmlFile = `<?xml version="1.0" encoding="UTF-8"?>
Тебе не нужен именно файл, тебе нужен просто js объект:

```javascript
const YCML = {
   yml_catalog: {
      shop: {
         categories: ....
      }
   }
}
```

```javascript
import { js2xml } from 'xml-js'

const xml = js2xml(YCML)

writeFileSync(xml, ...)
```

2022-11-29 12:15 UTC, TFK70 commented on prices/service-entrypoint/src/utils/pretty.util.ts
>  const pretty = (string: string): string =>
Да, лучше без него
И нам не нужно ведь наружу их экспортировать, мы в коде этот JSON потом нигде не читаем

2022-11-29 13:47 UTC, TFK70 approved these changes

2022-11-29 18:19 UTC, merged