chore(prices): logging
torin-asakura/shdvor pull request #41
Opened 2022-12-09 15:17 UTC by carminio

2022-12-09 15:32 UTC, TFK70 requested changes

2022-12-09 15:32 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
>  const task = cron.schedule('0 0 * * 0', () => {
Еще добавь сюда в самое начало лог о том, что таска началась

2022-12-09 15:32 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
>  const bootstrap = async () => {
И сюда в начале что приложение тип инициализируется

2022-12-09 15:32 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
>  task.start()
И сюда в конец еще сделай `bootstrap()` чтобы операция начиналась сразу когда ты запускаешь сервис

2022-12-12 10:40 UTC, TFK70 approved these changes

2022-12-12 11:33 UTC, TFK70 requested changes

2022-12-12 11:33 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
> +    fetchData(`${API_URL}${GOODS_LIST_PATH}?pageNumber=${index}`))
Тебе на вход из энва приходит хост, а не url
Я же кидал `FILES_STORAGE_HOST=storage.yandexcloud.net`

2022-12-12 11:38 UTC, TFK70 commented on prices/service-entrypoint/src/bootstrap.ts
> +    fetchData(`${API_URL}${GOODS_LIST_PATH}?pageNumber=${index}`))
Короче я это к тому что сервис при попытке синкнуть цены упал с таким логом:

```shell
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (/workspace/dist/index.js:49400:16)
    at /workspace/dist/index.js:49722:19
    at new Promise (<anonymous>)
    at fetch (/workspace/dist/index.js:49720:9)
    at fetchData (/workspace/dist/index.js:198:59)
    at bootstrap (/workspace/dist/index.js:20:54)
    at Task._execution (/workspace/dist/index.js:51:5) {
  input: 'undefined/Goods/list',
  code: 'ERR_INVALID_URL'
}
```

2022-12-12 11:39 UTC, TFK70 approved these changes

2022-12-12 21:23 UTC, TorinAsakura approved these changes

2022-12-12 21:24 UTC, merged