бамб версий app и blog, переход на app - роутер next js
torin-asakura/shdvor pull request #54
Opened 2024-08-05 15:57 UTC by effektivnayarabota1

closes - https://github.com/torin-asakura/shdvor/issues/52
closes - https://github.com/torin-asakura/shdvor/issues/53

2024-08-14 07:03 UTC, effektivnayarabota1 commented
@Nelfimov вроде все сделал. нужно чеки както запустить

2024-08-14 07:12 UTC, Nelfimov commented
> @Nelfimov вроде все сделал. нужно чеки както запустить

Чеки отдельно исправлять будем, тебе еще туда рано. Можешь на всякий случай еще попробовать:
- запустить `yarn dedupe` и запустить чеки
- удалить yarn.lock и кэш и запустить чеки

Будущие траблы с бандлом можешь создавать таски сюда https://github.com/atls/raijin

Проверь чтобы локал в точности совпадал со стейджем. Тогда смержим.

2024-08-14 07:24 UTC, effektivnayarabota1 commented
> Проверь чтобы локал в точности совпадал со стейджем. Тогда смержим.

ты имеешь ввиду визуально?

2024-08-14 07:25 UTC, Nelfimov commented
Да. Там пока нет никакой логики

2024-08-14 08:21 UTC, effektivnayarabota1 commented
> * удалить yarn.lock и кэш и запустить чеки

`typecheck` пришел, на `линте` та же ошибка

2024-08-16 11:03 UTC, Nelfimov requested changes
1. 1 ПР на обе таски - мы так не договаривались. 1 таска - 1 ПР
2. ПР в драфте
3. Тайтл на русском

2024-08-16 11:29 UTC, effektivnayarabota1 commented
> 1. 1 ПР на обе таски - мы так не договаривались. 1 таска - 1 ПР
> 2. ПР в драфте
> 3. Тайтл на русском

- в этой ветке оставил все правки, кроме правок в `blog`
- правки в `blog` вынес в [отдельный `ПР`](https://github.com/torin-asakura/shdvor/pull/55)
- ревью запросил на обоих `ПР`

2024-08-16 11:46 UTC, Nelfimov requested changes
аналогично другому ПР

2024-08-19 08:24 UTC, aliceinapple requested changes

2024-08-19 08:24 UTC, aliceinapple commented on ui/checkbox/package.json
> +    "@atls-ui-parts/checkbox": "^0.1.1",
версия

2024-08-19 08:24 UTC, aliceinapple commented on ui/checkbox/src/checkbox.component.tsx
> +const Checkmark = styled.div(
вынести в отдельный файл

2024-08-19 08:24 UTC, aliceinapple commented on ui/checkbox/src/checkbox.component.tsx
> +export const Checkbox: FC<CheckboxProps> = ({ children, active, onCheck = () => doNothing() }) => (
`memo`

2024-08-19 08:24 UTC, aliceinapple commented on ui/checkbox/src/checkbox.component.tsx
> +const doNothing = () => {
пустая функция

2024-08-19 08:24 UTC, aliceinapple commented on ui/condition/package.json
> +    "@types/react": "^18.3.3",
версия

2024-08-19 08:24 UTC, aliceinapple commented on ui/divider/package.json
> +    "react-dom": "^18.3.1",
версия

2024-08-19 08:24 UTC, aliceinapple commented on ui/gtag/src/gtag.component.tsx
> +export const Gtag: FC<GtagProps> = ({ gaTrackingId }) => {
`memo`

2024-08-19 08:24 UTC, aliceinapple commented on ui/progress-bar/src/progress-bar.ts
> +const ProgressBar = BaseProgressBar as unknown as any
`any`

2024-08-19 08:24 UTC, aliceinapple commented on ui/utils/src/hooks/use-hover.interface.ts
> +// import type { SetStateAction } from 'react'
комментарии

2024-08-19 08:44 UTC, aliceinapple commented
@effektivnayarabota1 

Еще не нашла папку с иконками в `ui/icons`
И в `blog` дублируется `next.config`

2024-08-21 12:38 UTC, effektivnayarabota1 commented on ui/progress-bar/src/progress-bar.ts
> +const ProgressBar = BaseProgressBar as unknown as any
вот этот `error` не понимаю, как обойти, поэтому сделал так
![image](https://github.com/user-attachments/assets/7fa7fd67-85e0-4a79-b7e8-2ae0e2fe4884)

2024-08-21 15:45 UTC, effektivnayarabota1 commented on blog/app/src/app/layout.tsx
> +export { generateMetadata } from '@blog/root-layout-fragment'
поместил эти значения в константу во фрагменте, но ведь их в любом случае нужно реэкспортировать на этом уровне?
https://nextjs.org/docs/app/api-reference/functions/generate-metadata

2024-08-22 10:10 UTC, aliceinapple requested changes

2024-08-22 10:10 UTC, aliceinapple commented on fragments/booking-fragment/package.json
> +    "react-dom": "^18.3.1"
Упустил

2024-08-23 06:52 UTC, aliceinapple approved these changes

2024-08-23 08:09 UTC, Nelfimov requested changes
аналогично исправить релиз

2024-08-29 05:32 UTC, merged