`blog` versions bump; move to `app-nextjs-router`
torin-asakura/shdvor pull request #55
Opened 2024-08-16 11:26 UTC by effektivnayarabota1

closes - https://github.com/torin-asakura/shdvor/issues/53

2024-08-16 11:46 UTC, Nelfimov commented
@aliceinapple чеки игнорируй. Надо посмотреть код и запустить локально. Референс - https://shdvor.pro

2024-08-16 11:47 UTC, Nelfimov requested changes
на ревью у Вики

2024-08-16 13:28 UTC, aliceinapple requested changes
- Вижу много дубликатов папок и компонентов, как во фрагментах, так и в страницах, пересмотри
- Дефолтные экспорты у компонентов и функций поменяй на обычные

@effektivnayarabota1  как ты запускаешь проект?

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/articles-fragment/src/article/return-button/return-button.component.tsx
> +const ReturnButton: FC<ReturnButtonProps> = ({ title }) => {
`memo`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/footer-fragment/package.json
> +    "@globals/data": "workspace:*",
`"workspace:0.0.1"`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/footer-fragment/src/footer-component.tsx
>  const Footer: FC<FooterProps> = ({ contactsData, fragmentsData }) => {
`memo`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/navigation-fragment/package.json
> +    "@fragments/booking-fragment": "workspace:*",
`"workspace:0.0.1"`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/root-layout-fragment/package.json
> +    "@globals/data": "workspace:*",
`"workspace:0.0.1"`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/root-layout-fragment/src/root-layout.component.tsx
> +export const RootLayout: FC<PropsWithChildren<RootLayoutProps>> = ({
`memo`

2024-08-16 13:28 UTC, aliceinapple commented on blog/fragments/root-layout-fragment/src/root-layout.component.tsx
> +import { Gtag }              from '@ui/gtag'
Не нашла такого пакета в `ui`

2024-08-16 13:28 UTC, aliceinapple commented on blog/pages/index-page/package.json
> +    "@blog/articles-fragment": "workspace:*",
Аналогично, как уже писала

2024-08-16 13:28 UTC, aliceinapple commented on blog/pages/post-page/package.json
> +    "@blog/articles-fragment": "workspace:*",
Аналогично, как писала

2024-08-16 13:44 UTC, effektivnayarabota1 commented
> @effektivnayarabota1 как ты запускаешь проект?

`yarn workspace @site/app dev`
`yarn workspace @blog/app dev`

2024-08-16 13:52 UTC, effektivnayarabota1 commented on blog/app/src/app/layout.tsx
> +export default RootLayout
по документации https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates

2024-08-16 13:56 UTC, aliceinapple commented on blog/app/src/app/layout.tsx
> +export default RootLayout
> по документации https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates

Для лэйаутов ок, просто тут рядом другие экспорты есть, нужны ли они менно в этом файле или можно вынести?

2024-08-22 08:31 UTC, aliceinapple requested changes

2024-08-22 08:31 UTC, aliceinapple commented on fragments/navigation-fragment/src/navigation-list-mobile/item/item.component.tsx
> +const Item: FC<ItemProps> = ({ active, content, title, scrollY }) => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on fragments/navigation-fragment/src/navigation-list-mobile/navigation-list-mobile.component.tsx
> +const NavigationListMobile: FC<NavigationListMobileProps> = ({ scrollY, active, navigation }) => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on fragments/navigation-fragment/src/navigation-list/item/item.component.tsx
> +const Item: FC<ItemProps> = ({ active, content, title, scrollY }) => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on fragments/navigation-fragment/src/navigation-list/navigation-list.component.tsx
> +const NavigationList: FC<NavigationListProps> = ({ active, scrollY, navigation }) => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on fragments/navigation-fragment/src/navigation.component.tsx
>  const Navigation: FC<NavigationProps> = ({
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on globals/data/package.json
> +    "@apollo/client": "^3.11.3",
Версии

2024-08-22 08:31 UTC, aliceinapple commented on globals/data/src/data/queries/work-results.query.ts
> +import { gql }       from '@apollo/client'
Обычно делим такой файл на `query` и `hook`

В файле `work-results.query.ts` - `const GET_WORK_RESULTS...`
В файле `work-results.hook.ts` - `useGetWorkResults` например

2024-08-22 08:31 UTC, aliceinapple commented on prices/service-entrypoint/package.json
> +    "aws-sdk": "^2.1667.0",
Версии

2024-08-22 08:31 UTC, aliceinapple commented on shared/utils/package.json
> +    "luxon": "^3.5.0"
Версии с `^`

2024-08-22 08:31 UTC, aliceinapple commented on site/fragments/contacts-fragment/src/contacts-information/contacts-information.component.tsx
> +export const ContactsInformation: FC<ContactsInformationProps> = (props) => {
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on site/fragments/contacts-fragment/src/map/map.component.tsx
> +export const MapComponent: FC = () => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on site/fragments/service-fragment/src/car-body-item/car-body-item.component.tsx
> +const CarBodyItem: FC<ItemProps> = ({ item }) => (
`memo`

2024-08-22 08:31 UTC, aliceinapple commented on store/actions/package.json
> +    "@apollo/client": "^3.11.3",
Версия

2024-08-22 08:31 UTC, aliceinapple commented on store/booking/package.json
> +    "@apollo/client": "^3.11.3",
версия

2024-08-22 08:37 UTC, aliceinapple commented on globals/data/src/data/queries/work-results.query.ts
> +import { gql }       from '@apollo/client'
Пока можешь оствить, это так, на будущее

2024-08-22 09:21 UTC, aliceinapple requested changes

2024-08-22 09:21 UTC, aliceinapple commented on prices/service-entrypoint/package.json
> +    "aws-sdk": "^2.1667.0",
Имела ввиду, тут и ниже замени версии на точные, без `^`

2024-08-22 09:36 UTC, effektivnayarabota1 commented
@aliceinapple `@prices` вообще не трогал, в любом случае обновил.

2024-08-22 10:01 UTC, aliceinapple approved these changes

2024-08-22 10:01 UTC, aliceinapple commented on fragments/navigation-fragment/src/helpers/get-color-background.ts
> +      return 'wite'
Поправь только на `white` и запрашивай ревью дальше

2024-08-23 06:32 UTC, Nelfimov requested changes
вмержи мастер. Надо убедиться, что релиз проходит. Остальные чеки поправим потом

2024-08-23 06:38 UTC, effektivnayarabota1 commented
> вмержи мастер. Надо убедиться, что релиз проходит. Остальные чеки поправим потом

done

2024-08-23 06:46 UTC, Nelfimov requested changes
проверяй конфиг next и остальные ошибки

https://github.com/torin-asakura/shdvor/actions/runs/10521134825/job/29151303817

конфиг можешь подсмотреть в том же тим менеджменте

2024-08-23 07:53 UTC, effektivnayarabota1 commented
> проверяй конфиг next и остальные ошибки
> 
> https://github.com/torin-asakura/shdvor/actions/runs/10521134825/job/29151303817
> 
> конфиг можешь подсмотреть в том же тим менеджменте

ошибка с функцией `withSentryConfig`

если экспортирую только `nextConfig`, то сборка проходит нормально

не могу понять, где выполняется этот код, на гитхабе `sentry` его не нашел
пробовал добавить `sentry` в `peerDeps` - не помогло

лог:
```ts
TypeError: Cannot destructure property 'sentryWebpackPlugin' of 'utils.loadModule(...)' as it is undefined.
```

2024-08-23 08:11 UTC, Nelfimov commented
@effektivnayarabota1 скорее всего есм или апп роутер конфликтует. Попробуй заново настроить - https://sentry.io/for/nextjs/

2024-08-23 12:09 UTC, effektivnayarabota1 commented
> @effektivnayarabota1 скорее всего есм или апп роутер конфликтует. Попробуй заново настроить - https://sentry.io/for/nextjs/

все по документации настраиваю, таже ошибка
запускал как `cjs` - работает, но внутренние зависимости не читает
https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/

2024-08-23 12:14 UTC, Nelfimov commented
попробуй переведи весь конфиг на commonjs

2024-08-23 13:40 UTC, effektivnayarabota1 commented
> попробуй переведи весь конфиг на commonjs

у меня вот такая пачка получается:
эта проблема решается если в `tsconfig` добавить `allowImportingTsExtensions`, но тогда, насколько я понимаю, придется перебивать все иморты по всему приложению.
сейчас ищу в документации `webpack` опцию, чтобы он менял `importextention`, но покачто не вижу. может быть ты знаешь как это можно сделать? и вообще можно ли?

```
../../.yarn/__virtual__/@fragments-global-error-fragment-virtual-0e7abfb98d/1/fragments/global-error-fragment/src/index.ts
Module not found: Can't resolve './global-error.component.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/global-error.tsx

../../.yarn/__virtual__/@blog-index-page-virtual-fa4b14909a/1/blog/pages/index-page/src/index.ts
Module not found: Can't resolve './index-page.component.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/page.tsx

../../.yarn/__virtual__/@blog-index-page-virtual-fa4b14909a/1/blog/pages/index-page/src/index.ts
Module not found: Can't resolve './index-page.constants.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/page.tsx

../../.yarn/__virtual__/@blog-post-page-virtual-12a9e826ee/1/blog/pages/post-page/src/index.ts
Module not found: Can't resolve './post-page.component.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/[uri]/page.ts

../../.yarn/__virtual__/@blog-post-page-virtual-12a9e826ee/1/blog/pages/post-page/src/index.ts
Module not found: Can't resolve './post-page.constants.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/[uri]/page.ts
```

2024-08-23 14:05 UTC, Nelfimov commented
выноси в отдельную задачу, убирай сентри и идем дальше

2024-08-24 11:43 UTC, Nelfimov requested changes
проверь у энтрипоинта `prepack` и `start`

2024-08-26 05:37 UTC, Nelfimov commented
@effektivnayarabota1 попробуй отказаться от генерации типов.

2024-08-26 16:33 UTC, effektivnayarabota1 commented
@Nelfimov 
- занимался `query` и их `getter-функциями`, `входящими тимпами`. закончил этот момент

- собрать `@blog` не получаетя, т.к. не все ошибки типов пофиксил

- работал в этой ветке - https://github.com/torin-asakura/shdvor/tree/refactor/reviews

2024-08-27 12:29 UTC, effektivnayarabota1 commented
@Nelfimov 

- **все типы для входящих данных прописал, все корректно**
1. есть две функции, которые модифицирую данные на уровне фрагментов (разбирают их). в этом нет проблем, просто эта функция рассчитанна для объектов разных типов, а объединить не получается почемуто
2. по п.1
3. по всему приложению не прописанны условия для `null | undefined` и он сыпет эти ошибки.

<details>
<summary>1</summary>

```ts
➤ YN0000: │ site/fragments/services-infographics-fragment/src/services-infographics.component.tsx:32:55
➤ YN0000: │ 
➤ YN0000: │ TS233: Property 'image' does not exist on type '{ __typename?: "Fragment_Contentaddons" | undefined; title?: string | null | undefined; content?: string | null | undefined; 
➤ YN0000: │      fragmentId?: string | null | undefined; highlightedtext?: string | ... 1 more ... | undefined; }'.
➤ YN0000: │ 
➤ YN0000: │   30 |
➤ YN0000: │   31 |   const extractFragmentImageData = (dataType: string): string =>
➤ YN0000: │ > 32 |     extractFragment('contentAddons', 'wheel', uiData)?.image[dataType]
➤ YN0000: │      |                                                       ^
➤ YN0000: │   33 |
➤ YN0000: │   34 |   const whellImgAltText = extractFragmentImageData('altText')
➤ YN0000: │   35 |   const whellImgSourceUrl = extractFragmentImageData('sourceUrl')
```

</details>

<details>
<summary>2</summary>

```ts
➤ YN0000: │ TS233: Property 'title' does not exist on type '{ __typename?: "Fragment_Contentaddons" | undefined; title?: string | null | undefined; content?: string | null | undefined; 
➤ YN0000: │      fragmentId?: string | null | undefined; highlightedtext?: string | ... 1 more ... | undefined; } | null | undefined'.
➤ YN0000: │ 
➤ YN0000: │   25 |   const services = extractFragments('service-item', 'servicesParams', servicesData)
➤ YN0000: │   26 |
➤ YN0000: │ > 27 |   const { title } = extractFragment('contentAddons', 'our-services', fragmentsData)
➤ YN0000: │      |          ^
➤ YN0000: │   28 |   const subTitle = extractFragment('contentAddons', 'select-needed-service', fragmentsData).title
➤ YN0000: │   29 |   const allServicesTitle = extractFragment('contentAddons', 'all-services', fragmentsData).title
```

</details>


<details>
<summary>3</summary>

```ts
➤ YN0000: │ TS232: Type '{ __typename?: "Service_Servicesparams_Additionalservice" | undefined; title?: string | null | undefined; price?: number | null | undefined; } | null | 
➤ YN0000: │      undefined' is not assignable to type '{ title: string; price: number; }'.
➤ YN0000: │        Type 'undefined' is not assignable to type '{ title: string; price: number; }'.
➤ YN0000: │ 
➤ YN0000: │   262 |                 isAdditionalService={isAdditionalService}
➤ YN0000: │   263 |                 setIsAdditionalService={setIsAdditionalService}
➤ YN0000: │ > 264 |                 additionalservice={additionalservice}
➤ YN0000: │       |                ^
➤ YN0000: │   265 |               />
➤ YN0000: │   266 |             </Condition>
➤ YN0000: │   267 |             <Layout flexBasis={32} />
```

</details>

2024-08-27 12:44 UTC, effektivnayarabota1 commented
@Nelfimov 
а как можно написать такой женерик, чтобы он работал как `useState`, тоесть `useState<boolean>(true)`

> 1. объектов разных типов

женерик сделал

2024-08-27 12:44 UTC, effektivnayarabota1 commented
> 3\. `null | undefined` и он сыпет эти ошибки.

на уровне фрагментов, после функции из п.1 буду назначать типы вручную, где возможно

2024-08-27 12:50 UTC, Nelfimov commented
@effektivnayarabota1 обвешай все `@ts-expect-error` с причиной ошибки

2024-08-27 15:33 UTC, effektivnayarabota1 commented
@Nelfimov 
- сборка должна запускаться с `sudo`?
- есть жалобы на отсутствующие `директории/файлы`, их же должен создавать скрипт сам?
```ts
 ⚠ Linting is disabled.
  ▲ Next.js 14.2.5
  - Experiments (use with caution):
    · externalDir
    · esmExternals
    · outputFileTracingRoot

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (4/4)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    658 B           352 kB
├ ○ /_not-found                          877 B          88.2 kB
└ ƒ /[uri]                               661 B           352 kB
+ First Load JS shared by all            87.3 kB
  ├ chunks/793-1093b19ed4bf7509.js       31.7 kB
  ├ chunks/8900b45f-0b6c84dd133c3c7c.js  53.7 kB
  └ other shared chunks (total)          1.94 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand

cp: cannot stat './src/.next/standalone': No such file or directory
```

2024-08-27 16:15 UTC, effektivnayarabota1 commented
@Nelfimov

# Текущий статус
- прописал те типы, что знал
- закрыл оставшиеся ошибки типов - `@ts-expect-error`
- запустил `prepack`, есть ошибки
# Дальнейшие планы
- разобраться с ошибками сборки. скорее всего чтото в конфигах

### log

<details>
<summary>Click to expand</summary>

 path: '/home/operator/work/atls_shdvor/blog/app/.next/server/chunks/528.js',
  dest: '/blog/app/.next/server/chunks/528.js'
}
 ⚠ Failed to copy traced files for /home/operator/work/atls_shdvor/blog/app/.next/server/app/[uri]/page.js [Error: EACCES: permission denied, copyfile '/home/operator/work/atls_shdvor/blog/app/.next/server/chunks/515.js' -> '/blog/app/.next/server/chunks/515.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'copyfile',
  path: '/home/operator/work/atls_shdvor/blog/app/.next/server/chunks/515.js',
  dest: '/blog/app/.next/server/chunks/515.js'
}
 ⚠ Failed to copy traced files for /home/operator/work/atls_shdvor/blog/app/.next/server/app/page.js [Error: EACCES: permission denied, copyfile '/home/operator/work/atls_shdvor/blog/app/.next/server/app/page_client-reference-manifest.js' -> '/blog/app/.next/server/app/page_client-reference-manifest.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'copyfile',
  path: '/home/operator/work/atls_shdvor/blog/app/.next/server/app/page_client-reference-manifest.js',
  dest: '/blog/app/.next/server/app/page_client-reference-manifest.js'
}

> Build error occurred
[Error: EACCES: permission denied, open '/blog/app/server.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/blog/app/server.js'
}

</details>


# Актуальная ветка

- https://github.com/torin-asakura/shdvor/tree/refactor/reviews

2024-08-28 08:50 UTC, effektivnayarabota1 commented
@Nelfimov 
- как скрипт именнует вложенные пакеты после билда?

```console
Error: Duplicate workspace name shdvor: /home/operator/work/atls_shdvor/blog/app/dist conflicts with /home/operator/work/atls_shdvor
    at t.addWorkspace (/home/operator/work/atls_shdvor/.yarn/releases/yarn.cjs:214:2912)
    at /home/operator/work/atls_shdvor/.yarn/releases/yarn.cjs:214:2709
```

2024-08-28 08:53 UTC, Nelfimov commented
> @Nelfimov
> 
> * как скрипт именнует вложенные пакеты после билда?
> 
> ```
> Error: Duplicate workspace name shdvor: /home/operator/work/atls_shdvor/blog/app/dist conflicts with /home/operator/work/atls_shdvor
>     at t.addWorkspace (/home/operator/work/atls_shdvor/.yarn/releases/yarn.cjs:214:2912)
>     at /home/operator/work/atls_shdvor/.yarn/releases/yarn.cjs:214:2709
> ```

Зависит от `next.config.js`

Вот пример рабочего https://github.com/atls-lab/frontend/blob/master/app-router/entrypoints/renderer/next.config.js

2024-08-28 09:12 UTC, Nelfimov commented
должно работать с текущим

2024-08-28 09:13 UTC, effektivnayarabota1 commented
@Nelfimov а какие еще `entrypoints` могут быть, помимо `renderer`?
![image](https://github.com/user-attachments/assets/7f64a551-7c32-4c90-9dc5-aa583abb6666)

2024-08-28 09:18 UTC, Nelfimov commented
> @Nelfimov а какие еще `entrypoints` могут быть, помимо `renderer`? ![image](https://private-user-images.githubusercontent.com/70315473/362218719-7f64a551-7c32-4c90-9dc5-aa583abb6666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzY5ODAsIm5iZiI6MTcyNDgzNjY4MCwicGF0aCI6Ii83MDMxNTQ3My8zNjIyMTg3MTktN2Y2NGE1NTEtN2MzMi00YzkwLTlkYzUtYWE1ODNhYmI2NjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5MTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZTZkY2UxY2M3NjRmNjk4Njc4ODk1YzM3MGQzNGViYjY3NGVlNWYxYTYyNTZiNGMwNjI4OGUwMGE1NmYwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ekO_lUItCs2Q3Tjh8lZzh1n-XnyCYzgSbacs0A1Li5I)

откуда это?

2024-08-28 09:26 UTC, effektivnayarabota1 commented
> > @Nelfimov а какие еще `entrypoints` могут быть, помимо `renderer`? ![image](https://private-user-images.githubusercontent.com/70315473/362218719-7f64a551-7c32-4c90-9dc5-aa583abb6666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzY5ODAsIm5iZiI6MTcyNDgzNjY4MCwicGF0aCI6Ii83MDMxNTQ3My8zNjIyMTg3MTktN2Y2NGE1NTEtN2MzMi00YzkwLTlkYzUtYWE1ODNhYmI2NjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5MTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZTZkY2UxY2M3NjRmNjk4Njc4ODk1YzM3MGQzNGViYjY3NGVlNWYxYTYyNTZiNGMwNjI4OGUwMGE1NmYwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ekO_lUItCs2Q3Tjh8lZzh1n-XnyCYzgSbacs0A1Li5I)
> 
> откуда это?

https://github.com/atls-lab/frontend/blob/master/app-router/entrypoints/renderer/next.config.js

2024-08-28 09:28 UTC, Nelfimov commented
не понимаю вопроса - у тебя есть энтрипоинт для фронта. Ему нужно задать конфиг чтобы был правильный билд.

2024-08-28 11:00 UTC, effektivnayarabota1 commented
@Nelfimov
- `yarn workspace @blog/app prepack` - работает
- `yarn workspace @blog/app start` - работает
- ревью запросил

2024-08-28 11:14 UTC, Nelfimov requested changes
приложи yarn.lock, экшен сломал

2024-08-28 11:31 UTC, Nelfimov requested changes
поправь еще конфиг у app

2024-08-28 11:40 UTC, effektivnayarabota1 commented
> поправь еще конфиг у app

если под `app` ты имеешь ввиду `@site/app`, то он у нас другим ПР висит, им сейчас занимаюсь

2024-08-28 11:43 UTC, Nelfimov approved these changes

2024-08-28 11:44 UTC, merged