change `@prices` to `ems`
torin-asakura/shdvor pull request #69
Opened 2024-08-29 10:16 UTC by effektivnayarabota1

closes https://github.com/torin-asakura/shdvor/issues/68

2024-08-29 10:18 UTC, effektivnayarabota1 commented
@Nelfimov 
- можем оставить `prettier` в руте? у меня он только так работает

2024-08-29 10:20 UTC, Nelfimov requested changes
Пользуйся `yarn format`

Ты тестировал приложение?

2024-08-29 10:21 UTC, effektivnayarabota1 commented
> Ты тестировал приложение?

занимаюсь

2024-08-29 11:04 UTC, effektivnayarabota1 commented
@Nelfimov 

- `node-cron` просит `__dirname`
- нашел аналогичный пакет - https://www.npmjs.com/package/cron
- будем менять или есть другие способы, как это можно исправить?

<details>
<summary>log</summary>

```ts
➤ YN0000: ┌ Service Development
➤ YN0000: │  Starting server...
➤ YN0000: │  webpack-internal:///../.yarn/berry/cache/node-cron-npm-3.0.3-fd539f5b81-10.zip/node_modules/node-cron/src/background-scheduled-task/index.js:6
➤ YN0000: │  const daemonPath = `${__dirname}/daemon.js`;
➤ YN0000: │                     ^
➤ YN0000: │  ReferenceError: __dirname is not defined in ES module scope
➤ YN0000: │  This file is being treated as an ES module because it has a '.js' file extension and '/home/operator/work/atls_shdvor/prices/service-entrypoint/package.json'
➤ YN0000: │  contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
➤ YN0000: │      at eval (webpack-internal:///../.yarn/berry/cache/node-cron-npm-3.0.3-fd539f5b81-10.zip/node_modules/node-cron/src/background-scheduled-task/index.js:6:20)
➤ YN0000: │      at ../.yarn/berry/cache/node-cron-npm-3.0.3-fd539f5b81-10.zip/node_modules/node-cron/src/background-scheduled-task/index.js
➤ YN0000: │  (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:1778:1)
➤ YN0000: │      at __webpack_require__ (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:17617:32)
➤ YN0000: │      at fn (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:17779:20)
➤ YN0000: │      at eval (webpack-internal:///../.yarn/berry/cache/node-cron-npm-3.0.3-fd539f5b81-10.zip/node_modules/node-cron/src/node-cron.js:4:33)
➤ YN0000: │      at ../.yarn/berry/cache/node-cron-npm-3.0.3-fd539f5b81-10.zip/node_modules/node-cron/src/node-cron.js
➤ YN0000: │  (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:1848:1)
➤ YN0000: │      at __webpack_require__ (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:17617:32)
➤ YN0000: │      at fn (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:17779:20)
➤ YN0000: │      at eval (webpack-internal:///./prices/service-entrypoint/src/bootstrap.ts:31:37)
➤ YN0000: │      at ./prices/service-entrypoint/src/bootstrap.ts (file:///home/operator/work/atls_shdvor/prices/service-entrypoint/dist/index.js:2718:1)
➤ YN0000: │  Node.js v19.9.0
```

</details>

2024-08-29 11:05 UTC, Nelfimov commented
Давай попробуем с аналогом

2024-08-29 12:51 UTC, effektivnayarabota1 commented
@Nelfimov а я могу узнать вот этот параметр, чтобы запустить тест с локалки?
```ts
export const API_URL = process.env.API_URL
```

2024-08-29 14:24 UTC, Nelfimov commented
@effektivnayarabota1 https://api.aqsi.ru/pub/v2

2024-08-29 15:26 UTC, effektivnayarabota1 commented
@Nelfimov `aqsi` настроить себе под тесты или могу также подключить наш ключ, чтобы использовать готовые данные?

2024-08-29 17:17 UTC, Nelfimov commented
Завтра с утра напомни

2024-08-30 06:39 UTC, effektivnayarabota1 commented
> Завтра с утра напомни

напоминаю

2024-08-30 07:00 UTC, effektivnayarabota1 commented
> > > Завтра с утра напомни
> > 
> > 
> > напоминаю
> 
> Мне проще будет локально запустить. Приведи в порядок ветку и маякуй - отпишусь по статусу запуска

все готово

2024-08-30 08:24 UTC, Nelfimov commented
@effektivnayarabota1 подтверждаю - работает. Причесывай и отдавай на ревью

2024-08-30 08:50 UTC, Nelfimov approved these changes

2024-08-30 08:51 UTC, merged