make `ssr` on `@site`
torin-asakura/shdvor pull request #71
Opened 2024-08-29 14:44 UTC by effektivnayarabota1

2024-08-29 14:45 UTC, effektivnayarabota1 commented
@Nelfimov ревью пока не нужно, не вижу как могу его отменить

2024-08-29 15:02 UTC, Nelfimov requested changes
на доработку

2024-08-29 15:02 UTC, Nelfimov commented
@effektivnayarabota1 свои TODO файлы добавь в гитигнор раз уж пользуешься

2024-08-29 16:10 UTC, effektivnayarabota1 commented
@Nelfimov подскажи пожалуйста что такое `oathkeeper`
```ts
export const serverUri =
  process.env.NODE_ENV === 'production'
    ? 'http://oathkeeper:4455/gateway'
    : 'http://oathkeeper:4455/gateway/'
```

2024-08-29 17:19 UTC, Nelfimov commented
> @Nelfimov `oathkeeper` это оно https://www.ory.sh/docs/oathkeeper?

Это оно.

> - я пока не знаю как это работает, но делать через неё?
> 
> ```ts
> 
> export const serverUri =
> 
>   process.env.NODE_ENV === 'production'
> 
>     ? 'http://oathkeeper:4455/gateway'
> 
>     : 'http://oathkeeper:4455/gateway/'
> 
> ```

В твоем случае этого разделения нет, поэтому пишешь один адрес. 

Попозже дойдем и до oathkeeper

2024-09-06 05:25 UTC, Nelfimov requested changes
1. `site` - принимается. Отличная работа!
    Надо будет проверить в стейдже скорость загрузки
    
2. `blog` - при переходе на конкретные статьи падает ошибка. Напр. http://localhost:3000/hranenie-shin-2 - `Failed to load resource: Cannot use wildcard in Access-Control-Allow-
Origin when credentials flag is true.`

2024-09-06 08:26 UTC, effektivnayarabota1 commented
> 2\. при переходе на конкретные статьи падает ошибка

- проверил в `webkit`-браузере, все ок. приложил видео
- на сервере и клиенте `apollo` стоит опция: `credentials: 'include'`
- перепроверил `@site` (страница "услуги" сделанна идентично, в плане `apollo`)

https://github.com/user-attachments/assets/fa61b9bd-1de3-467b-9def-b2e301ade060

2024-09-06 08:32 UTC, Nelfimov commented
Запускал в том числе в инкогнито:

Safari

https://github.com/user-attachments/assets/0e0b4207-cdad-40fb-9ac3-8f4208aca0fd

![Screenshot 2024-09-06 at 11 29 25](https://github.com/user-attachments/assets/29e10780-0a7f-4d67-9757-a266b3f5217e)

Chrome

https://github.com/user-attachments/assets/b0bdaa3c-4781-4082-9ef2-82d2ddbca87a

2024-09-06 15:51 UTC, effektivnayarabota1 commented
@Nelfimov сделал `fetch` в итоге, с интерфейсом `apollo` не удалось разобраться
не понимаю, ведь если и `queries` и `mutations` уходят с одного клиента, то и в первом случе была бы ошибка?

в доках вот такая информация есть:
https://www.apollographql.com/docs/react/data/mutations#mutationhookoptions-interface-context
![image](https://github.com/user-attachments/assets/0e385de4-401a-4410-96fe-7e3669eaa2fd)

2024-09-06 15:54 UTC, Nelfimov commented
> @Nelfimov сделал `fetch` в итоге, с интерфейсом `apollo` не удалось разобраться не понимаю, ведь если и `queries` и `mutations` уходят с одного клиента, то и в первом случе была бы ошибка?

У тебя два разных клиента - один для сервера один для клиента.

Посмотри в сторону `*`. Если ничего не найдешь - отправим в стейдж и проверим там.

2024-09-06 16:09 UTC, effektivnayarabota1 commented
> У тебя два разных клиента - один для сервера один для клиента.

на сервере тоже пробовал эту мутацию. ошибки не было, но она не проходила, значения не менялись

> *

про звездочку не понял

> Если ничего не найдешь - отправим в стейдж и проверим там.

щас все работает, я от ошибки избавился. просто использовал не `useMutation` а `fetch` вручную прописал

2024-09-07 07:20 UTC, Nelfimov requested changes
вернуть `useMutation`

2024-09-09 06:54 UTC, Nelfimov approved these changes

2024-09-09 06:55 UTC, merged