feat: booking telegram bot
torin-asakura/shdvor pull request #97
Opened 2024-09-17 09:04 UTC by effektivnayarabota1

closes https://github.com/torin-asakura/shdvor/issues/70

2024-09-17 09:04 UTC, effektivnayarabota1 commented
@Nelfimov ревью не нужно, в процессе

2024-09-17 09:20 UTC, Nelfimov commented
> @Nelfimov ревью не нужно, в процессе

А зачем тогда меня призываешь?

2024-09-17 09:24 UTC, Nelfimov requested changes

2024-09-17 09:24 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bootstrap.ts
> +// declare const module: {
не коммить закоменченный код. Иначе буду требовать сквошей

2024-09-17 09:24 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bootstrap.ts
> +  // TODO for what?
это чтобы работал вебпак hmr

2024-09-17 09:24 UTC, Nelfimov commented on package.json
> +    "booking-telegram-bot/**/*"
прогоняй так же `yarn tools sync`

2024-09-17 09:24 UTC, Nelfimov commented on booking-telegram-bot/adapters/telegram-adapter/package.json
> +  "license": "MIT",
`BSD-3-Clause`

2024-09-17 09:24 UTC, Nelfimov commented on booking-telegram-bot/adapters/telegram-adapter/package.json
> +  "main": "src/index.ts",
`exports`

2024-09-17 09:24 UTC, Nelfimov commented on booking-telegram-bot/adapters/telegram-adapter/package.json
> +    "@nestjs/common": "10.4.2",
это в пиры

2024-09-19 12:05 UTC, Nelfimov requested changes

2024-09-19 12:05 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/module/telegram-bot.infrastructure.module.ts
> +  static registerAsync(): DynamicModule {
1. это не `async`
2. тут не добавил возвращаемый тип, из-за чего см. ниже

2024-09-19 12:05 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/module/telegram-bot.infrastructure.module.ts
> +      exports: [...providers],
глупейшая ошибка

2024-09-19 12:05 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/index.ts
> +export * from './services/index.js'
тут не экспортировал сервис, из-за чего твой порт `...Impl` не знал что инжектить

2024-09-19 12:05 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/services/tgsnake-adapter.service.ts
> +export class TgsnakeAdapterService extends Snake {
не воспользовался ооп

2024-09-30 11:09 UTC, kirill-ivanovvv commented
@Nelfimov 
- типы не прописывал, потомучто нужно уточнение. кажется, что не на том уровне использую `ctx`. `ctx` передается между объектами на уровне `services` - хотя имеет тип объекта из  библиотеки `tgsnake` - тоесть, если мы поменяем `telegram-bot-adapter`, то тип `ctx` у нас изменится.
- функционал бд не писал - выносил общие методы в родительские классы, чистил функции. добавил парочку ts-интерфейсов - в целом, рефактор пятничной версии приложения, без нового функционала
- есть список тудушек среднего размера, отправляю на ревью текущую версию
- ревью запросил

2024-09-30 11:28 UTC, Nelfimov requested changes
почини релиз - этот ПР будем мержить в мастер

2024-09-30 13:30 UTC, kirill-ivanovvv commented
`credentials` зашиты в адаптер
https://t.me/atls_shdvor_booking_bot

2024-09-30 13:30 UTC, kirill-ivanovvv commented
@Nelfimov 
`credentials` зашиты в адаптер
https://t.me/atls_shdvor_booking_bot

2024-09-30 14:02 UTC, Nelfimov requested changes
1. `graphql-client` в контекстах - очень под большим вопросом. Сам рассуди - контекст это область, в рамках которой выполняется функционал приложения. А ты его завязываешь на конкретный интерфейс - graphql. А если будем использовать http? или websocket? Замечание относится не только к неймингу, но и смыслу за этим контекстом
2. `application` у бота надо все свести к useCase. Сервисы - это уже не к месту. Ну и задавай себе вопрос - должен ли `application` знать как работает конкретная библиотека. Если нет - выноси в порт

По итогу чтобы вмержить текущий прогресс:
1. исправить `graphql-client` контекст
2. исправить `application` у бота
3. добавить интерфейсы

2024-09-30 14:02 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/services/appointment-conversation/appointment-conversation.service.ts
> +export class AppointmentConversationService {
это скорее useCase

2024-09-30 14:02 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/locals/index.ts
> +export { default as ruLocale } from './ru.json'
тут локали не место - только в адаптерах

2024-10-08 05:40 UTC, Nelfimov requested changes
1. остались не учтенные комменты
2. в application лезет все извне

2024-10-08 05:40 UTC, Nelfimov commented on .vim/prettier.config.cjs
>  module.exports = {
убери из гита `.vim`

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/adapters/apollo-adapter/src/client/index.ts
> +export * from './apollo.client.js'
не дает там оставить коммент.

Обычно URL для коннекта выносят в env с фоллбэком

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/adapters/apollo-adapter/src/services/apollo-adapter.service.ts
> +export class ApolloAdapterService implements ApolloAdapterInt {
поставь TODO - надо разбить этот класс на более мелкие

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/services/tgsnake-adapter.service.ts
> +export class TgsnakeAdapterService extends Snake {
TODO - надо будет так же разбить на мелкие классы

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "tgsnake": "*"
не исправил

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bootstrap.ts
> +  accept: VoidFunction
не выполнил - эти аттрибуты не используются

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bootstrap.ts
> +  const app = await NestFactory.create(BotServiceEntrypointModule, {
не выполнил

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/entrypoints/service-entrypoint/src/bootstrap.ts
> +  const processor = app.get(BotListenProcessor)
это и ниже - если хочешь что-то запускать на старте - `OnModuleInit`

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/infrastructure-module/src/processors/bot-listen.processor.ts
> +export class BotListenProcessor {
`TODO` - разбить на несколько процессор для отдельной команды

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/contexts/graphql-client/application-module/package.json
> +    "@globals/data": "workspace:*"
не выполнил

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/locals/index.ts
> +export { default as ruLocale } from './ru.json'
`TODO` на вынос

2024-10-08 05:40 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/ports/telegram-client.port.ts
> +import type { CreateConversationReturnType }    from '@booking-telegram-bot/tgsnake-adapter'
еще раз - `application` не знает и не должен знать что происходит вне его. А тут ты говоришь ему - возьми типы из адаптера и infrastructure

2024-10-08 06:21 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/apollo-adapter/src/client/index.ts
> +export * from './apollo.client.js'
названия env-переменных имеет смысле вынести, например, в `README`?

2024-10-08 06:28 UTC, Nelfimov commented on booking-telegram-bot/adapters/apollo-adapter/src/client/index.ts
> +export * from './apollo.client.js'
Можно, необязательно

2024-10-08 06:30 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/graphql-client/application-module/package.json
> +    "@globals/data": "workspace:*"
`globals` тоже нельзя?
`queries` дублирую в `application`?

2024-10-08 06:33 UTC, Nelfimov commented on booking-telegram-bot/contexts/graphql-client/application-module/package.json
> +    "@globals/data": "workspace:*"
ты можешь использовать `globals` в адаптере

2024-10-08 07:17 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/ports/telegram-client.port.ts
> +import type { CreateConversationReturnType }    from '@booking-telegram-bot/tgsnake-adapter'
если определять типы на уровне `application` - могу их переиспользовать и в `infrastructure` и в `adapter`?

2024-10-08 07:35 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/ports/telegram-client.port.ts
> +import type { CreateConversationReturnType }    from '@booking-telegram-bot/tgsnake-adapter'
зачем? Ты в `application` определяешь минимально необходимый интерфейс для работы приложения. А в адаптере и инфраструктуре можешь использовать что угодно

2024-10-08 07:49 UTC, kirill-ivanovvv commented
@Nelfimov при мерже текущий ишью закроется и нужно будет создать новый - типо продолжение бота? или не будем ишью закрывать?

2024-10-08 08:23 UTC, Nelfimov requested changes
опять часть замечания не выполнены. Соберись

2024-10-08 08:23 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "tgsnake": "3.3.1"
а тут что делает?

2024-10-08 08:23 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "@telegram-bot/infrastructure-module": "workspace:*"
а здесь что происходит?

2024-10-08 08:23 UTC, Nelfimov commented on booking-telegram-bot/contexts/query-client/application-module/package.json
> +  "devDependencies": {
есть подозрение что здесь опять не хватает `rxjs` и прочих

2024-10-08 08:23 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/ports/telegram-client.port.ts
> +import type { CreateConversationReturnType }    from '@booking-telegram-bot/tgsnake-adapter'
не выполнено

2024-10-08 08:23 UTC, Nelfimov commented on booking-telegram-bot/contexts/telegram-bot/application-module/src/services/conversation-part.class.ts
> +class ConversationPart {
не выполнено

2024-10-08 08:31 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "tgsnake": "3.3.1"
`tgsnake` же должен в билд попасть. а в билд попадают только `dev` зависимости?
https://github.com/torin-asakura/shdvor/pull/97#discussion_r1781160879

2024-10-08 08:33 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "tgsnake": "3.3.1"
это работает только в энтрипоинте. Остальные пакеты - как обычно

2024-10-08 08:34 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "@telegram-bot/infrastructure-module": "workspace:*"
я в `infrastructure` определили `formatted-context-type` и импортирую его в адаптер. 
в адаптере внутри функций с контекстом написал миддлвер, который форматирует под наш тип

или ты имеешь ввиду, что я не в тот тип зависимостей прописал этот пакет?

2024-10-08 08:36 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "@telegram-bot/infrastructure-module": "workspace:*"
Должна быть цепочка адаптер -> инфраструктура, не наоборот

2024-10-08 08:37 UTC, kirill-ivanovvv commented on booking-telegram-bot/contexts/query-client/application-module/package.json
> +  "devDependencies": {
как понять? ошибок при запуске не было

2024-10-08 08:38 UTC, Nelfimov commented on booking-telegram-bot/contexts/query-client/application-module/package.json
> +  "devDependencies": {
когда запускаешь `yarn` - посмотри лог зависимостей

2024-10-08 09:52 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/package.json
> +    "tgsnake": "3.3.1"
я тебя линчую.

`dependencies` - то что нужно пакету для работы и что он ни от куда больше не получит

`peerDependencies` - то что нужно для работы и что пакет может получить от своих родителей

`devDependencies` - то что нужно для разработки

Вот у тебя в пирах `@nestjs/common`. Ты знаешь что получишь его от родителей - ок. А почему он у тебя вдруг оказался в `dependencies`? Ты ожидаешь его от родителей но еще устанавливаешь отдельно?

Обычно практика такая - все что ждешь от `peerDependencies` и используешь в коде, то добавляешь в `devDependencies`. Тогда и соблюдается логика:
- я получу эту зависимость от родителей, но чтобы работать нормально с кодом мне нужна эта зависимость в `devDependencies`

2024-10-08 09:54 UTC, Nelfimov approved these changes
пропускаю со следующими замечаниями:
- зависимости - наведи порядок в пирах и дев зависимостях
- нейминг - ConversationQA? Никаких сокращений
- разобраться с `application` в боте - у тебя каждый useCase - отдельный сценарий использования приложения. То что ты разложил беседу на сервисы - хорошо. Вероятно стоит это разложение перенести в несколько useCase

2024-10-08 09:54 UTC, merged

2024-10-15 06:33 UTC, kirill-ivanovvv commented on booking-telegram-bot/adapters/tgsnake-adapter/src/services/tgsnake-adapter.service.ts
> +export class TgsnakeAdapterService extends Snake {
> TODO - надо будет так же разбить на мелкие классы

а как этот класс разбить на более мелкие, если в конструкторе инициализируется `tsnake-client`

разделить `tgsnake-клиент` и `use-кейсы` и на уровне инфраструктуры инджектитть `tsnake-client` и этот клиент забрасывать в use-кейсы?

2024-10-15 06:38 UTC, Nelfimov commented on booking-telegram-bot/adapters/tgsnake-adapter/src/services/tgsnake-adapter.service.ts
> +export class TgsnakeAdapterService extends Snake {
нет, речь только про адаптер.

Выделяешь отдельно tgsnake как провайдер. Его инжектишь в адаптере в разные классы. Каждый класс - отдельный сервис для работы с чем либо. Сообщения, команды, беседы и т.д.